#!/usr/bin/env python3
"""Regenerate the table of contents inside a Markdown file, in place.

    python3 tools/docs/toc.py specs/product/specs.md
    python3 tools/docs/toc.py --check specs/product/specs.md   # exit 1 if stale

The ToC is written between the two marker comments below, which must already
exist in the file. Everything outside them is left byte-for-byte alone.

WHY A SCRIPT AND NOT A HAND-WRITTEN LIST: a 2500-line spec's contents page goes
stale on the first heading rename, and a stale contents page is worse than none
— it sends a reader to the wrong section and looks authoritative doing it.

WHY THE ANCHORS ARE NOT GUESSED: GitHub derives a heading's anchor with a
specific algorithm (lowercase, drop everything that is not alphanumeric, space,
hyphen or underscore, spaces to hyphens, then `-1`, `-2` … for repeats).
`slugify` below reproduces it, and `tools/docs/verify-toc.py` checks the result
against GitHub's own renderer rather than trusting this comment.

Deliberately NOT wired into CI: a docs ToC drifting is a nuisance, not a defect,
and the repo pays for CI by the job.
"""
from __future__ import annotations

import argparse
import pathlib
import re
import sys

BEGIN = "<!-- toc:begin — generated by tools/docs/toc.py; do not edit by hand -->"
END = "<!-- toc:end -->"

# A fenced code block can contain lines that look like headings.
FENCE = re.compile(r"^(```|~~~)")
HEADING = re.compile(r"^(#{1,3}) +(.*?)\s*#*\s*$")

# Inline markdown that must not reach either the label or the anchor.
LINK = re.compile(r"\[([^\]]*)\]\([^)]*\)")
CODE = re.compile(r"`([^`]*)`")


def slugify(text: str, seen: dict[str, int]) -> str:
    """GitHub's heading-anchor algorithm, including its duplicate suffixes."""
    slug = text.strip().lower()
    slug = re.sub(r"[^\w\- ]", "", slug, flags=re.UNICODE)
    slug = slug.replace(" ", "-")
    count = seen.get(slug, 0)
    seen[slug] = count + 1
    return slug if count == 0 else f"{slug}-{count}"


def headings(lines: list[str], toc_span: tuple[int, int] | None):
    in_fence = False
    for index, line in enumerate(lines):
        if toc_span and toc_span[0] <= index <= toc_span[1]:
            continue
        if FENCE.match(line):
            in_fence = not in_fence
            continue
        if in_fence:
            continue
        match = HEADING.match(line)
        if match:
            yield len(match.group(1)), match.group(2)


def build(lines: list[str], toc_span: tuple[int, int] | None) -> list[str]:
    seen: dict[str, int] = {}
    out: list[str] = []
    for level, raw in headings(lines, toc_span):
        # The anchor is derived from the heading's rendered text, so links and
        # code spans contribute their INNER text, not their markup.
        text = CODE.sub(r"\1", LINK.sub(r"\1", raw))
        anchor = slugify(text, seen)
        if level == 1:
            continue  # the document title and part headings anchor the sections below
        indent = "  " * (level - 2)
        out.append(f"{indent}- [{text}](#{anchor})")
    return out


def toc_for(path: pathlib.Path) -> tuple[str, str]:
    original = path.read_text()
    lines = original.splitlines()

    try:
        begin = next(i for i, line in enumerate(lines) if line.strip() == BEGIN)
        end = next(i for i, line in enumerate(lines) if line.strip() == END)
    except StopIteration:
        sys.exit(
            f"{path}: markers not found. Add these two lines where the ToC belongs:\n"
            f"  {BEGIN}\n  {END}"
        )
    if end < begin:
        sys.exit(f"{path}: toc:end appears before toc:begin")

    # Part headings (level 1) are kept as bare section labels so the tree has a
    # spine; they are emitted here rather than in build() because build() also
    # walks the section bodies.
    # The heading the ToC lives under — "## Contents" or whatever it is called —
    # is skipped: a contents list whose first entry is itself is pure noise, and
    # a reader who is reading it has already arrived.
    own_heading = next(
        (HEADING.match(lines[i]).group(2) for i in range(begin - 1, -1, -1) if HEADING.match(lines[i])),
        None,
    )

    seen: dict[str, int] = {}
    body: list[str] = []
    for level, raw in headings(lines, (begin, end)):
        text = CODE.sub(r"\1", LINK.sub(r"\1", raw))
        # Slugified even when skipped: GitHub still numbers it, so dropping it
        # from `seen` would shift every duplicate suffix after it.
        anchor = slugify(text, seen)
        if text == own_heading:
            continue
        if level == 1:
            body.append(f"- **[{text}](#{anchor})**")
        else:
            body.append(f"{'  ' * (level - 1)}- [{text}](#{anchor})")

    # The first level-1 heading is the document title; a ToC that links to the
    # title of the page it is on is noise.
    if body and body[0].startswith("- **["):
        body = body[1:]

    rebuilt = lines[: begin + 1] + [""] + body + [""] + lines[end:]
    return original, "\n".join(rebuilt) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("path", type=pathlib.Path)
    parser.add_argument("--check", action="store_true", help="exit 1 if the ToC is stale")
    args = parser.parse_args()

    original, rebuilt = toc_for(args.path)
    if args.check:
        if original != rebuilt:
            print(f"{args.path}: table of contents is stale — run tools/docs/toc.py {args.path}")
            return 1
        print(f"{args.path}: table of contents is current")
        return 0

    if original == rebuilt:
        print(f"{args.path}: already current")
        return 0
    args.path.write_text(rebuilt)
    print(f"{args.path}: table of contents regenerated")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
