#!/usr/bin/env python3
"""Regenerate the table of contents inside a Markdown file, in place.

    python3 tools/docs/toc.py specs/product/specs.md
    python3 tools/docs/toc.py --check specs/product/specs.md   # exit 1 if stale

The ToC is written between the two marker comments below, which must already
exist in the file. Everything outside them is left byte-for-byte alone.

WHY A SCRIPT AND NOT A HAND-WRITTEN LIST: a 2500-line spec's contents page goes
stale on the first heading rename, and a stale contents page is worse than none
— it sends a reader to the wrong section and looks authoritative doing it.

WHY THE ANCHORS ARE NOT GUESSED: GitHub derives a heading's anchor with a
specific algorithm (lowercase, drop everything that is not alphanumeric, space,
hyphen or underscore, spaces to hyphens, then `-1`, `-2` … for repeats).
`slugify` below reproduces it, and `tools/docs/verify-toc.py` checks the result
against GitHub's own renderer rather than trusting this comment.

Deliberately NOT wired into CI: a docs ToC drifting is a nuisance, not a defect,
and the repo pays for CI by the job.
"""
from __future__ import annotations

import argparse
import pathlib
import re
import sys

BEGIN = "<!-- toc:begin — generated by tools/docs/toc.py; do not edit by hand -->"
END = "<!-- toc:end -->"

# A fenced code block can contain lines that look like headings, so the block
# has to be tracked accurately: a fence closed EARLY exposes its contents, and
# every `##` in there becomes a ToC entry pointing at an anchor GitHub never
# emitted. CommonMark's three rules that matter here, each of which produced a
# dead link when it was missing:
#
#   * the opening fence may be indented by up to three spaces;
#   * a fence closes only on the SAME character — a `~~~` line inside a ```
#     block is content, not a close;
#   * the closing run must be at least as long as the opening one, and must
#     carry no info string;
#   * a BACKTICK opener's info string may not contain a backtick. That shape is
#     a paragraph holding an inline code span, and reading it as a fence opens a
#     block that never closes — swallowing every heading in the rest of the file
#     and emitting an empty contents page.
FENCE = re.compile(r"^ {0,3}(`{3,}|~{3,})[ \t]*(.*?)\s*$")

# Like a fence, an ATX heading may be indented up to three spaces (four makes it
# an indented code block instead) and may be separated from its text by a tab.
# GitHub emits an anchor for both, so a matcher demanding column zero and a
# literal space drops the section from the contents without failing.
#
# The trailing group strips an ATX *closing* sequence (`## Heading ##`), which
# CommonMark requires to be preceded by whitespace. `#*` without that `\s+`
# would also eat a hash that is part of the text — `## C#` would render a
# heading reading "C#" while the ToC linked a label reading "C".
HEADING = re.compile(r"^ {0,3}(#{1,3})[ \t]+(.*?)(?:\s+#+)?\s*$")

# A setext underline: `===` (level 1) or `---` (level 2) under its heading text.
# Matched only to REFUSE the file — see `setext_underlines`.
SETEXT = re.compile(r"^ {0,3}(=+|-+)[ \t]*$")

# Inline markdown that must not reach either the label or the anchor.
LINK = re.compile(r"\[([^\]]*)\]\([^)]*\)")
CODE = re.compile(r"`([^`]*)`")


def slugify(text: str, seen: dict[str, int]) -> str:
    """GitHub's heading-anchor algorithm, including its duplicate suffixes."""
    slug = text.strip().lower()
    slug = re.sub(r"[^\w\- ]", "", slug, flags=re.UNICODE)
    slug = slug.replace(" ", "-")
    count = seen.get(slug, 0)
    seen[slug] = count + 1
    return slug if count == 0 else f"{slug}-{count}"


def content_lines(lines: list[str], toc_span: tuple[int, int] | None):
    """Yield `(index, line)` for prose: outside fences, frontmatter and the ToC."""
    start = 0
    if lines and lines[0].strip() == "---":
        # YAML frontmatter. Its closing `---` sits under a non-blank line and is
        # otherwise indistinguishable from a setext underline.
        for i in range(1, len(lines)):
            if lines[i].strip() in {"---", "..."}:
                start = i + 1
                break

    opener: str | None = None  # the run that opened the current block, e.g. "```"
    for index in range(start, len(lines)):
        line = lines[index]
        if toc_span and toc_span[0] <= index <= toc_span[1]:
            continue
        fence = FENCE.match(line)
        if fence:
            run, info = fence.group(1), fence.group(2)
            if opener is not None:
                if run[0] == opener[0] and len(run) >= len(opener) and not info:
                    opener = None
                # Anything else is a fence-shaped line INSIDE a block — content.
                continue
            if not (run[0] == "`" and "`" in info):
                opener = run
                continue
            # An invalid backtick opener is ordinary prose. Fall through; a line
            # starting with backticks cannot match HEADING anyway, but it must
            # not be allowed to open a block.
        if opener is not None:
            continue
        yield index, line


def headings(lines: list[str], toc_span: tuple[int, int] | None):
    """Yield `(line index, level, raw text)` for every heading outside the ToC."""
    for index, line in content_lines(lines, toc_span):
        match = HEADING.match(line)
        if match:
            yield index, len(match.group(1)), match.group(2)


def setext_underlines(lines: list[str], toc_span: tuple[int, int] | None) -> list[int]:
    """Line numbers (1-based) of setext underlines this tool refuses to model.

    A setext heading — text with `===` or `---` under it — gets an anchor from
    GitHub exactly like an ATX one, so ignoring it silently drops a real section
    from the contents page. Supporting it is the wrong trade: the underline is
    ambiguous with a thematic break, a table rule and a frontmatter terminator,
    and every misread INVENTS an entry pointing at an anchor that does not
    exist. A missing entry is recoverable; a confident wrong link is not.

    So the tool refuses the input instead of guessing at it. A survey of all 150
    tracked markdown files found no setext heading and two look-alikes, both of
    the ambiguous kind above — which is the argument for this being a guard
    rather than a feature.
    """
    prose = dict(content_lines(lines, toc_span))
    found = []
    for index, line in prose.items():
        if not SETEXT.match(line):
            continue
        above = prose.get(index - 1)
        if above is None or not above.strip():
            continue  # a thematic break, not an underline
        if HEADING.match(above) or SETEXT.match(above):
            continue
        found.append(index + 1)
    return found


def rebuild(original: str, label: str = "<text>") -> str:
    """Return `original` with the region between the markers replaced by a ToC."""
    lines = original.splitlines()

    try:
        begin = next(i for i, line in enumerate(lines) if line.strip() == BEGIN)
        end = next(i for i, line in enumerate(lines) if line.strip() == END)
    except StopIteration:
        sys.exit(
            f"{label}: markers not found. Add these two lines where the ToC belongs:\n"
            f"  {BEGIN}\n  {END}"
        )
    if end < begin:
        sys.exit(f"{label}: toc:end appears before toc:begin")

    # Level-1 headings are kept as bare section labels so the tree has a spine.
    #
    # The heading the ToC lives under — "## Contents" or whatever it is called —
    # is skipped: a contents list whose first entry is itself is pure noise, and
    # a reader who is reading it has already arrived.
    #
    # Identified by its LINE, not by its text. Matching on text also suppressed
    # any later heading that happened to render the same — a second "## Contents"
    # section would silently vanish from the contents while GitHub still gave it
    # an anchor (`contents-1`).
    #
    # Taken from `headings()` rather than by scanning raw lines backwards, so a
    # fenced code block sitting above the markers cannot supply a fake one.
    # Refuse rather than silently omit. Checked here, not in `main`, so both
    # `--check` and the rewrite path go through it.
    setext = setext_underlines(lines, (begin, end))
    if setext:
        sys.exit(
            f"{label}: setext headings on line(s) "
            + ", ".join(str(n) for n in setext)
            + " — this tool only models ATX headings (`## Title`). GitHub gives a\n"
            "setext heading an anchor, so listing nothing for it would be a silent\n"
            "omission. Convert them to ATX, or teach the tool and pin a case."
        )

    found = list(headings(lines, (begin, end)))
    own_heading_line = max((i for i, _, _ in found if i < begin), default=None)

    seen: dict[str, int] = {}
    body: list[str] = []
    for index, level, raw in found:
        text = CODE.sub(r"\1", LINK.sub(r"\1", raw))
        # Slugified even when skipped: GitHub still numbers it, so dropping it
        # from `seen` would shift every duplicate suffix after it.
        anchor = slugify(text, seen)
        if index == own_heading_line:
            continue
        if level == 1:
            body.append(f"- **[{text}](#{anchor})**")
        else:
            body.append(f"{'  ' * (level - 1)}- [{text}](#{anchor})")

    # The first level-1 heading is the document title; a ToC that links to the
    # title of the page it is on is noise.
    if body and body[0].startswith("- **["):
        body = body[1:]

    rebuilt = lines[: begin + 1] + [""] + body + [""] + lines[end:]
    return "\n".join(rebuilt) + "\n"


def toc_for(path: pathlib.Path) -> tuple[str, str]:
    original = path.read_text()
    return original, rebuild(original, str(path))


# Heading parsing is the part of this tool that can be wrong *quietly* — a
# mangled label still produces a plausible-looking contents line. The `## C#`
# case is the one that shipped: `#*` at the end of the pattern ate a hash that
# belonged to the text (codex review, PR #551).
HEADING_CASES = [
    ("## C#", "C#"),
    ("## F# and C#", "F# and C#"),
    ("## Heading ##", "Heading"),
    ("### Deep ###", "Deep"),
    ("## Plain", "Plain"),
    ("## Trailing spaces   ", "Trailing spaces"),
    ("## 8.1 States", "8.1 States"),
    ("## A # B", "A # B"),
    ("   ## Indented", "Indented"),
    ("##\tTabbed", "Tabbed"),
    # Four spaces is an indented code block, not a heading — GitHub emits no
    # anchor for it, so matching it would invent a link to nowhere.
    ("    ## Four spaces is a code block", None),
]


# Document-level cases: each is (name, markdown, must contain, must NOT contain).
# All three came out of the PR #551 review — they are the failures that produce a
# plausible-looking contents page pointing at anchors GitHub never emitted.
DOCUMENT_CASES = [
    (
        # With a fence indented past the matcher, the `## Fake` inside the block
        # looks exactly like a heading — GitHub renders it as code and emits no
        # anchor, so the entry links nowhere. The heading here sits at column 0
        # only to keep the case pointed at the FENCE rule; since headings may
        # now be indented too, an indented one inside the block would leak the
        # same way.
        "an indented fence still hides a column-0 heading inside it",
        "# T\n\n## Contents\n\n" + BEGIN + "\n" + END + "\n\n## Real\n\n   ```text\n## Fake\n   ```\n",
        ["- [Real](#real)"],
        ["Fake"],
    ),
    (
        # A fence closes only on its OWN character. Treating `~~~` as a close
        # for a ``` block exposes the rest of the block, and then the real
        # closing ``` reads as an OPEN — so this loses real headings after the
        # block as well as inventing fake ones inside it.
        "a tilde line does not close a backtick fence",
        "# T\n\n## Contents\n\n" + BEGIN + "\n" + END
        + "\n\n## Real\n\n```text\n~~~\n## Fake\n```\n\n## After\n",
        ["- [Real](#real)", "- [After](#after)"],
        ["Fake"],
    ),
    (
        # The closing run must be at least as long as the opening one.
        "a shorter run does not close a longer fence",
        "# T\n\n## Contents\n\n" + BEGIN + "\n" + END
        + "\n\n## Real\n\n````text\n```\n## Fake\n````\n\n## After\n",
        ["- [Real](#real)", "- [After](#after)"],
        ["Fake"],
    ),
    (
        # A fence carrying an info string opens; it never closes.
        "a fence with an info string does not close a block",
        "# T\n\n## Contents\n\n" + BEGIN + "\n" + END
        + "\n\n## Real\n\n```text\n```js\n## Fake\n```\n\n## After\n",
        ["- [Real](#real)", "- [After](#after)"],
        ["Fake"],
    ),
    (
        # The worst failure this tool has: the phantom opener never closes, so
        # EVERY heading after it disappears and the contents page comes out
        # empty rather than merely wrong.
        "a backtick run with a backtick in its info string is not a fence",
        "# T\n\n## Contents\n\n" + BEGIN + "\n" + END + "\n\n```sh`x`\n\n## Real\n",
        ["- [Real](#real)"],
        [],
    ),
    (
        "an indented heading and a tab-separated heading are both listed",
        "# T\n\n## Contents\n\n" + BEGIN + "\n" + END + "\n\n   ## Indented\n\n##\tTabbed\n",
        ["- [Indented](#indented)", "- [Tabbed](#tabbed)"],
        [],
    ),
    (
        "a later heading matching the ToC's own is kept, with GitHub's suffix",
        "# T\n\n## Contents\n\n" + BEGIN + "\n" + END + "\n\n## Real\n\n## Contents\n",
        ["- [Real](#real)", "- [Contents](#contents-1)"],
        [],
    ),
    (
        "the enclosing contents heading itself is not listed",
        "# T\n\n## Contents\n\n" + BEGIN + "\n" + END + "\n\n## Real\n",
        ["- [Real](#real)"],
        ["(#contents)"],
    ),
    (
        # The enclosing heading is found through `headings()`, so a fenced block
        # between it and the markers cannot supply a fake one. A raw backwards
        # scan lands on the `## Fake` line inside the fence, skips a heading that
        # was never listed anyway, and leaves "Contents" listing itself.
        "a fence above the markers cannot supply a fake enclosing heading",
        "# T\n\n## Contents\n\n```text\n## Fake\n```\n\n" + BEGIN + "\n" + END + "\n\n## Real\n",
        ["- [Real](#real)"],
        ["(#contents)", "Fake"],
    ),
]


# Refusing an input is only safe if the refusal is precise: a guard that fires
# on a thematic break or a frontmatter terminator would reject files it handles
# correctly. Both directions are pinned. `(name, markdown, refused line numbers)`.
SETEXT_CASES = [
    ("text underlined with equals is refused", "# T\n\nTitle\n=====\n", [4]),
    ("text underlined with dashes is refused", "# T\n\nTitle\n-----\n", [4]),
    ("a thematic break after a blank line is not an underline", "# T\n\nPara\n\n---\n", []),
    ("a frontmatter terminator is not an underline", "---\ntitle: x\n---\n\n# T\n", []),
    ("an underline inside a fence is not an underline", "# T\n\n```\nPara\n---\n```\n", []),
    ("a break under an ATX heading is not an underline", "# T\n\n## H\n---\n", []),
    ("a table rule is not an underline", "# T\n\n| a |\n|---|\n| b |\n", []),
]


def self_test() -> int:
    failures = 0
    for name, source, expected in SETEXT_CASES:
        got = setext_underlines(source.splitlines(), None)
        if got != expected:
            failures += 1
            print(f"FAIL  {name}: refused lines {got}, expected {expected}")

    # The detector being right is worthless if `rebuild` does not consult it, and
    # every case above would stay green with the call deleted. Pin the wiring.
    wiring = "# T\n\n## Contents\n\n" + BEGIN + "\n" + END + "\n\nOops\n----\n"
    try:
        rebuild(wiring, "wiring")
    except SystemExit as exit_:
        if "setext" not in str(exit_):
            failures += 1
            print(f"FAIL  rebuild refuses a setext document: wrong message {str(exit_)!r}")
    else:
        failures += 1
        print("FAIL  rebuild refuses a setext document: it returned a ToC instead")

    for line, expected in HEADING_CASES:
        match = HEADING.match(line)
        got = match.group(2) if match else None
        if got != expected:
            failures += 1
            print(f"FAIL  heading {line!r} -> {got!r}, expected {expected!r}")

    for name, source, expected, forbidden in DOCUMENT_CASES:
        # Assert on the GENERATED BLOCK, not the whole document: the document
        # still contains the fenced `## Fake` line as code, so a whole-file
        # search would fail a case the tool actually handles correctly.
        whole = rebuild(source, name)
        produced = whole.split(BEGIN, 1)[1].split(END, 1)[0]
        for needle in expected:
            if needle not in produced:
                failures += 1
                print(f"FAIL  {name}: missing {needle!r}\n{produced}")
        for needle in forbidden:
            if needle in produced:
                failures += 1
                print(f"FAIL  {name}: unexpected {needle!r}\n{produced}")

    print(
        f"{len(HEADING_CASES)} heading cases + {len(DOCUMENT_CASES)} document cases "
        f"+ {len(SETEXT_CASES)} setext cases, {failures} failed"
    )
    return 1 if failures else 0


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("path", type=pathlib.Path, nargs="?")
    parser.add_argument("--check", action="store_true", help="exit 1 if the ToC is stale")
    parser.add_argument("--self-test", action="store_true", help="check the heading parser only")
    args = parser.parse_args()

    if args.self_test:
        return self_test()
    if args.path is None:
        parser.error("a path is required unless --self-test is given")

    original, rebuilt = toc_for(args.path)
    if args.check:
        if original != rebuilt:
            print(f"{args.path}: table of contents is stale — run tools/docs/toc.py {args.path}")
            return 1
        print(f"{args.path}: table of contents is current")
        return 0

    if original == rebuilt:
        print(f"{args.path}: already current")
        return 0
    args.path.write_text(rebuilt)
    print(f"{args.path}: table of contents regenerated")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
