#!/usr/bin/env python3
"""Regenerate the table of contents inside a Markdown file, in place.

    python3 tools/docs/toc.py specs/product/specs.md
    python3 tools/docs/toc.py --check specs/product/specs.md   # exit 1 if stale

The ToC is written between the two marker comments below, which must already
exist in the file. Everything outside them is left byte-for-byte alone.

WHY A SCRIPT AND NOT A HAND-WRITTEN LIST: a 2500-line spec's contents page goes
stale on the first heading rename, and a stale contents page is worse than none
— it sends a reader to the wrong section and looks authoritative doing it.

WHY THE ANCHORS ARE NOT GUESSED: GitHub derives a heading's anchor with a
specific algorithm (lowercase, drop everything that is not alphanumeric, space,
hyphen or underscore, spaces to hyphens, then `-1`, `-2` … for repeats).
`slugify` below reproduces it, and `tools/docs/verify-toc.py` checks the result
against GitHub's own renderer rather than trusting this comment.

Deliberately NOT wired into CI: a docs ToC drifting is a nuisance, not a defect,
and the repo pays for CI by the job.
"""
from __future__ import annotations

import argparse
import pathlib
import re
import sys

BEGIN = "<!-- toc:begin — generated by tools/docs/toc.py; do not edit by hand -->"
END = "<!-- toc:end -->"

# A fenced code block can contain lines that look like headings. CommonMark
# allows a fence to be indented by up to three spaces, and an indented fence
# left unrecognised means every `##` inside that block becomes a ToC entry
# pointing at an anchor GitHub never emitted.
FENCE = re.compile(r"^ {0,3}(```|~~~)")

# The trailing group strips an ATX *closing* sequence (`## Heading ##`), which
# CommonMark requires to be preceded by whitespace. `#*` without that `\s+`
# would also eat a hash that is part of the text — `## C#` would render a
# heading reading "C#" while the ToC linked a label reading "C".
HEADING = re.compile(r"^(#{1,3}) +(.*?)(?:\s+#+)?\s*$")

# Inline markdown that must not reach either the label or the anchor.
LINK = re.compile(r"\[([^\]]*)\]\([^)]*\)")
CODE = re.compile(r"`([^`]*)`")


def slugify(text: str, seen: dict[str, int]) -> str:
    """GitHub's heading-anchor algorithm, including its duplicate suffixes."""
    slug = text.strip().lower()
    slug = re.sub(r"[^\w\- ]", "", slug, flags=re.UNICODE)
    slug = slug.replace(" ", "-")
    count = seen.get(slug, 0)
    seen[slug] = count + 1
    return slug if count == 0 else f"{slug}-{count}"


def headings(lines: list[str], toc_span: tuple[int, int] | None):
    """Yield `(line index, level, raw text)` for every heading outside the ToC."""
    in_fence = False
    for index, line in enumerate(lines):
        if toc_span and toc_span[0] <= index <= toc_span[1]:
            continue
        if FENCE.match(line):
            in_fence = not in_fence
            continue
        if in_fence:
            continue
        match = HEADING.match(line)
        if match:
            yield index, len(match.group(1)), match.group(2)


def rebuild(original: str, label: str = "<text>") -> str:
    """Return `original` with the region between the markers replaced by a ToC."""
    lines = original.splitlines()

    try:
        begin = next(i for i, line in enumerate(lines) if line.strip() == BEGIN)
        end = next(i for i, line in enumerate(lines) if line.strip() == END)
    except StopIteration:
        sys.exit(
            f"{label}: markers not found. Add these two lines where the ToC belongs:\n"
            f"  {BEGIN}\n  {END}"
        )
    if end < begin:
        sys.exit(f"{label}: toc:end appears before toc:begin")

    # Level-1 headings are kept as bare section labels so the tree has a spine.
    #
    # The heading the ToC lives under — "## Contents" or whatever it is called —
    # is skipped: a contents list whose first entry is itself is pure noise, and
    # a reader who is reading it has already arrived.
    #
    # Identified by its LINE, not by its text. Matching on text also suppressed
    # any later heading that happened to render the same — a second "## Contents"
    # section would silently vanish from the contents while GitHub still gave it
    # an anchor (`contents-1`).
    own_heading_line = next(
        (i for i in range(begin - 1, -1, -1) if HEADING.match(lines[i])),
        None,
    )

    seen: dict[str, int] = {}
    body: list[str] = []
    for index, level, raw in headings(lines, (begin, end)):
        text = CODE.sub(r"\1", LINK.sub(r"\1", raw))
        # Slugified even when skipped: GitHub still numbers it, so dropping it
        # from `seen` would shift every duplicate suffix after it.
        anchor = slugify(text, seen)
        if index == own_heading_line:
            continue
        if level == 1:
            body.append(f"- **[{text}](#{anchor})**")
        else:
            body.append(f"{'  ' * (level - 1)}- [{text}](#{anchor})")

    # The first level-1 heading is the document title; a ToC that links to the
    # title of the page it is on is noise.
    if body and body[0].startswith("- **["):
        body = body[1:]

    rebuilt = lines[: begin + 1] + [""] + body + [""] + lines[end:]
    return "\n".join(rebuilt) + "\n"


def toc_for(path: pathlib.Path) -> tuple[str, str]:
    original = path.read_text()
    return original, rebuild(original, str(path))


# Heading parsing is the part of this tool that can be wrong *quietly* — a
# mangled label still produces a plausible-looking contents line. The `## C#`
# case is the one that shipped: `#*` at the end of the pattern ate a hash that
# belonged to the text (codex review, PR #551).
HEADING_CASES = [
    ("## C#", "C#"),
    ("## F# and C#", "F# and C#"),
    ("## Heading ##", "Heading"),
    ("### Deep ###", "Deep"),
    ("## Plain", "Plain"),
    ("## Trailing spaces   ", "Trailing spaces"),
    ("## 8.1 States", "8.1 States"),
    ("## A # B", "A # B"),
]


# Document-level cases: each is (name, markdown, must contain, must NOT contain).
# All three came out of the PR #551 review — they are the failures that produce a
# plausible-looking contents page pointing at anchors GitHub never emitted.
DOCUMENT_CASES = [
    (
        # The fence is indented, the line inside it is NOT: that is the shape
        # that breaks. With a fence indented past the matcher, the column-0
        # `## Fake` inside the block looks exactly like a heading — GitHub
        # renders it as code and emits no anchor, so the entry links nowhere.
        # (An indented `## Fake` would be skipped anyway: the heading matcher
        # requires column 0, which costs a missing entry, never a dead link.)
        "an indented fence still hides a column-0 heading inside it",
        "# T\n\n## Contents\n\n" + BEGIN + "\n" + END + "\n\n## Real\n\n   ```text\n## Fake\n   ```\n",
        ["- [Real](#real)"],
        ["Fake"],
    ),
    (
        "a later heading matching the ToC's own is kept, with GitHub's suffix",
        "# T\n\n## Contents\n\n" + BEGIN + "\n" + END + "\n\n## Real\n\n## Contents\n",
        ["- [Real](#real)", "- [Contents](#contents-1)"],
        [],
    ),
    (
        "the enclosing contents heading itself is not listed",
        "# T\n\n## Contents\n\n" + BEGIN + "\n" + END + "\n\n## Real\n",
        ["- [Real](#real)"],
        ["(#contents)"],
    ),
]


def self_test() -> int:
    failures = 0
    for line, expected in HEADING_CASES:
        match = HEADING.match(line)
        got = match.group(2) if match else None
        if got != expected:
            failures += 1
            print(f"FAIL  heading {line!r} -> {got!r}, expected {expected!r}")

    for name, source, expected, forbidden in DOCUMENT_CASES:
        # Assert on the GENERATED BLOCK, not the whole document: the document
        # still contains the fenced `## Fake` line as code, so a whole-file
        # search would fail a case the tool actually handles correctly.
        whole = rebuild(source, name)
        produced = whole.split(BEGIN, 1)[1].split(END, 1)[0]
        for needle in expected:
            if needle not in produced:
                failures += 1
                print(f"FAIL  {name}: missing {needle!r}\n{produced}")
        for needle in forbidden:
            if needle in produced:
                failures += 1
                print(f"FAIL  {name}: unexpected {needle!r}\n{produced}")

    print(
        f"{len(HEADING_CASES)} heading cases + {len(DOCUMENT_CASES)} document cases, "
        f"{failures} failed"
    )
    return 1 if failures else 0


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("path", type=pathlib.Path, nargs="?")
    parser.add_argument("--check", action="store_true", help="exit 1 if the ToC is stale")
    parser.add_argument("--self-test", action="store_true", help="check the heading parser only")
    args = parser.parse_args()

    if args.self_test:
        return self_test()
    if args.path is None:
        parser.error("a path is required unless --self-test is given")

    original, rebuilt = toc_for(args.path)
    if args.check:
        if original != rebuilt:
            print(f"{args.path}: table of contents is stale — run tools/docs/toc.py {args.path}")
            return 1
        print(f"{args.path}: table of contents is current")
        return 0

    if original == rebuilt:
        print(f"{args.path}: already current")
        return 0
    args.path.write_text(rebuilt)
    print(f"{args.path}: table of contents regenerated")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
