// #243 k6 harness — shared config.
//
// Base URL, CSRF header, auth paths, and the `.sim-cast.json` cast loader.
// `.sim-cast.json` is generated by `tools/simulation/bootstrap.sh` and is
// git-ignored (real per-run credentials) — never hardcode values from it
// here.

// k6 only allows `open()` in the init context (module top level), so the
// cast file is read once when this module is loaded, not lazily inside a
// function called from setup()/default(). The path is relative to *this*
// file's directory regardless of which script imports config.js.
const rawCast = JSON.parse(open('../.sim-cast.json'));

export const BASE_URL = __ENV.BASE_URL || 'http://127.0.0.1:8081';

// Presence-only CSRF guard the API requires on /auth/refresh — any value is
// accepted, but the header must be present. See
// src/Cluckwork.Api/Endpoints/Auth/AuthCookies.cs (CsrfHeaderName).
export const CSRF_HEADER_NAME = 'X-Cluckwork-Auth';
export const CSRF_HEADER_VALUE = '1';

// Name of the HttpOnly/Secure refresh-token cookie the API sets. Secure +
// plain HTTP loopback means k6's cookie jar will never resend it, so every
// consumer must extract and re-send it manually (see auth.js).
export const REFRESH_COOKIE_NAME = 'cluckwork_rt';

export const AUTH_PATHS = {
  LOGIN: '/api/v1/auth/login',
  REFRESH: '/api/v1/auth/refresh',
};

// Handy for smoke/bundle scripts that need an authed GET to prove a session
// is live; not strictly part of the auth surface.
export const ME_PATH = '/api/v1/me';

/**
 * Flattened cast list, owner first: [{ email, password, role }, ...].
 * Each call re-flattens the already-parsed `.sim-cast.json` object (no
 * re-reading the file — `open()` already ran once at module init).
 */
export function loadCastUsers() {
  const owner = { ...rawCast.owner };
  const cast = rawCast.cast.map((member) => ({ ...member }));
  return [owner, ...cast];
}
