namespace Cluckwork.Application.Tests.Architecture;

using System.Text;

public static class CouplingMatrix
{
    private const string Header = "<!-- generated by CouplingMatrix from module-ledger.json and the three walks; do not edit; regenerate by running the CouplingMatrixRealTreeTests with CLUCKWORK_REGENERATE_MATRIX=1 -->";

    // This last copy of §3.4 exists only to compare its module-cell letters with the generated cells.
    private static readonly (string From, string To, string Design)[] HandWrittenModuleCells =
    [
        ("Access", "Access", "—"),
        ("Access", "Farm", "R"),
        ("Access", "FlockManagement", "R"),
        ("Access", "EggOperations", "—"),
        ("Access", "Commerce", "—"),
        ("Access", "GeneralInventory", "—"),
        ("Access", "Finance", "—"),
        ("Access", "Insights", "E"),
        ("Farm", "Access", "—"),
        ("Farm", "Farm", "—"),
        ("Farm", "FlockManagement", "—"),
        ("Farm", "EggOperations", "—"),
        ("Farm", "Commerce", "—"),
        ("Farm", "GeneralInventory", "—"),
        ("Farm", "Finance", "—"),
        ("Farm", "Insights", "E"),
        ("FlockManagement", "Access", "—"),
        ("FlockManagement", "Farm", "R"),
        ("FlockManagement", "FlockManagement", "—"),
        ("FlockManagement", "EggOperations", "—"),
        ("FlockManagement", "Commerce", "—"),
        ("FlockManagement", "GeneralInventory", "—"),
        ("FlockManagement", "Finance", "—"),
        ("FlockManagement", "Insights", "E"),
        ("EggOperations", "Access", "—"),
        ("EggOperations", "Farm", "R"),
        ("EggOperations", "FlockManagement", "W"),
        ("EggOperations", "EggOperations", "—"),
        ("EggOperations", "Commerce", "—"),
        ("EggOperations", "GeneralInventory", "—"),
        ("EggOperations", "Finance", "—"),
        ("EggOperations", "Insights", "E"),
        ("Commerce", "Access", "—"),
        ("Commerce", "Farm", "R"),
        ("Commerce", "FlockManagement", "—"),
        ("Commerce", "EggOperations", "W"),
        ("Commerce", "Commerce", "—"),
        ("Commerce", "GeneralInventory", "—"),
        ("Commerce", "Finance", "—"),
        ("Commerce", "Insights", "E"),
        ("GeneralInventory", "Access", "—"),
        ("GeneralInventory", "Farm", "R"),
        ("GeneralInventory", "FlockManagement", "R"),
        ("GeneralInventory", "EggOperations", "—"),
        ("GeneralInventory", "Commerce", "—"),
        ("GeneralInventory", "GeneralInventory", "—"),
        ("GeneralInventory", "Finance", "—"),
        ("GeneralInventory", "Insights", "E"),
        ("Finance", "Access", "—"),
        ("Finance", "Farm", "W"),
        ("Finance", "FlockManagement", "R"),
        ("Finance", "EggOperations", "—"),
        ("Finance", "Commerce", "—"),
        ("Finance", "GeneralInventory", "—"),
        ("Finance", "Finance", "—"),
        ("Finance", "Insights", "E"),
        ("Insights", "Access", "—"),
        ("Insights", "Farm", "—"),
        ("Insights", "FlockManagement", "—"),
        ("Insights", "EggOperations", "—"),
        ("Insights", "Commerce", "—"),
        ("Insights", "GeneralInventory", "—"),
        ("Insights", "Finance", "—"),
        ("Insights", "Insights", "—"),
    ];

    public static string Render(ModuleLedger ledger, ModuleLedgerReport edges, TableOwnerReport tables,
        AdapterReachReport adapters)
    {
        var owners = OrderedOwners(ledger);
        var modules = owners.Where(owner => owner.Kind == ModuleLedger.ModuleKind).ToList();
        var platform = owners.Single(owner => owner.Kind == ModuleLedger.PlatformKind);
        var builder = new StringBuilder();

        builder.AppendLine(Header);
        builder.AppendLine();
        builder.AppendLine("`W` is synchronous write coupling and `R` is read or validation coupling. `E` after-commit events and `Q` read-model queries are not syntactically observable, so this file does not report them. `P` is the free Platform hub, `A` is a Platform adapter reach count, and `—` means no live edge.");
        builder.AppendLine();
        AppendMatrix(builder, ledger, edges, tables, adapters, modules, platform);
        builder.AppendLine();
        AppendForeignKeys(builder, tables);
        builder.AppendLine();
        AppendDifferences(builder, ledger, edges, tables, modules);
        return builder.ToString();
    }

    public static IReadOnlySet<(string From, string To)> LiveModulePairs(ModuleLedger ledger,
        ModuleLedgerReport edges)
    {
        var kinds = ledger.Owners.ToDictionary(owner => owner.Name, owner => owner.Kind, StringComparer.Ordinal);
        return edges.LiveEdges.Where(edge => kinds.GetValueOrDefault(edge.From) == ModuleLedger.ModuleKind
                && kinds.GetValueOrDefault(edge.To) == ModuleLedger.ModuleKind)
            .Select(edge => (edge.From, edge.To)).ToHashSet();
    }

    private static IReadOnlyList<OwnerDefinition> OrderedOwners(ModuleLedger ledger) => ledger.Owners
        .Where(owner => owner.Kind == ModuleLedger.ModuleKind)
        .Concat(ledger.Owners.Where(owner => owner.Kind == ModuleLedger.PlatformKind))
        .ToList();

    private static void AppendMatrix(StringBuilder builder, ModuleLedger ledger, ModuleLedgerReport edges,
        TableOwnerReport tables, AdapterReachReport adapters, IReadOnlyList<OwnerDefinition> modules,
        OwnerDefinition platform)
    {
        builder.Append("| from / to");
        foreach (var owner in modules.Append(platform))
        {
            builder.Append(" | ").Append(owner.Name);
        }
        builder.AppendLine(" |");
        builder.Append("|---");
        foreach (var _ in modules.Append(platform))
        {
            builder.Append("|---:");
        }
        builder.AppendLine("|");

        foreach (var row in modules)
        {
            builder.Append("| ").Append(row.Name);
            foreach (var column in modules)
            {
                builder.Append(" | ").Append(ModuleCell(ledger, edges, tables, row.Name, column.Name));
            }
            builder.Append(" | P |").AppendLine();
        }

        builder.Append("| ").Append(platform.Name);
        foreach (var column in modules)
        {
            var count = adapters.LiveReach.Where(reach => reach.Owner == column.Name)
                .Select(reach => reach.Symbol).Distinct(StringComparer.Ordinal).Count();
            builder.Append(" | ").Append(count == 0 ? "—" : $"A ({count})");
        }
        builder.AppendLine(" | — |");
    }

    private static string ModuleCell(ModuleLedger ledger, ModuleLedgerReport edges, TableOwnerReport tables,
        string from, string to)
    {
        var live = edges.LiveEdges.Where(edge => edge.From == from && edge.To == to).ToList();
        if (live.Count == 0)
        {
            return "—";
        }

        var kind = ledger.Edges.Single(cell => cell.From == from && cell.To == to).Kind;
        var symbols = live.Select(edge => edge.Symbol).Distinct(StringComparer.Ordinal).Count();
        var foreignKeys = tables.CrossOwnerForeignKeys.Count(foreignKey => foreignKey.From == from && foreignKey.To == to);
        return foreignKeys == 0 ? $"{kind} ({symbols})" : $"{kind} ({symbols}) fk:{foreignKeys}";
    }

    private static void AppendForeignKeys(StringBuilder builder, TableOwnerReport tables)
    {
        builder.AppendLine("## Cross-owner foreign keys");
        builder.AppendLine();
        builder.AppendLine("| name | table | from | to |");
        builder.AppendLine("|---|---|---|---|");
        foreach (var foreignKey in tables.CrossOwnerForeignKeys)
        {
            builder.Append("| ").Append(foreignKey.Name).Append(" | ").Append(foreignKey.Table)
                .Append(" | ").Append(foreignKey.From).Append(" | ").Append(foreignKey.To).AppendLine(" |");
        }
    }

    private static void AppendDifferences(StringBuilder builder, ModuleLedger ledger, ModuleLedgerReport edges,
        TableOwnerReport tables, IReadOnlyList<OwnerDefinition> modules)
    {
        builder.AppendLine("## Differences from the 2026-08 hand-written matrix");
        builder.AppendLine();
        builder.AppendLine("| from | to | hand-written | generated |");
        builder.AppendLine("|---|---|---|---|");
        var moduleNames = modules.Select(module => module.Name).ToHashSet(StringComparer.Ordinal);
        foreach (var cell in HandWrittenModuleCells.Where(cell => moduleNames.Contains(cell.From)
                     && moduleNames.Contains(cell.To)
                     && cell.Design is "W" or "R" or "—"
                     && KindOf(ModuleCell(ledger, edges, tables, cell.From, cell.To)) != cell.Design))
        {
            builder.Append("| ").Append(cell.From).Append(" | ").Append(cell.To).Append(" | ")
                .Append(cell.Design).Append(" | ").Append(ModuleCell(ledger, edges, tables, cell.From, cell.To))
                .AppendLine(" |");
        }
    }

    private static string KindOf(string cell) => cell == "—" ? cell : cell[..1];
}
