namespace Cluckwork.Application.Tests.Architecture;

using System.Text;

public static class CouplingMatrix
{
    private const string Header = "<!-- generated by CouplingMatrix from module-ledger.json and the three walks; do not edit; regenerate by running the CouplingMatrixRealTreeTests with CLUCKWORK_REGENERATE_MATRIX=1 -->";

    private static readonly string[] HandWrittenColumns =
    [
        "Access", "Farm", "FlockManagement", "EggOperations", "Commerce", "GeneralInventory", "Finance",
        "Insights", "Platform",
    ];

    // This is the final retained copy of the complete §3.4 hand-written matrix. It exists only for its diff.
    private static readonly (string From, string[] Cells)[] HandWrittenMatrix =
    [
        ("Access", ["—", "R", "R", "—", "—", "—", "—", "E", "P"]),
        ("Farm", ["—", "—", "—", "—", "—", "—", "—", "E", "P"]),
        ("FlockManagement", ["—", "R", "—", "—", "—", "—", "—", "E", "P"]),
        ("EggOperations", ["—", "R", "W", "—", "—", "—", "—", "E", "P"]),
        ("Commerce", ["—", "R", "—", "W", "—", "—", "—", "E", "P"]),
        ("GeneralInventory", ["—", "R", "R", "—", "—", "—", "—", "E", "P"]),
        ("Finance", ["—", "W", "R", "—", "—", "—", "—", "E", "P"]),
        ("Insights", ["—", "—", "—", "—", "—", "—", "—", "—", "Q/P"]),
        ("Platform/adapters", ["W", "W", "W", "W", "W", "W", "W", "R", "—"]),
    ];

    public static string Render(ModuleLedger ledger, ModuleLedgerReport edges, TableOwnerReport tables,
        AdapterReachReport adapters)
    {
        var owners = OrderedOwners(ledger);
        var modules = owners.Where(owner => owner.Kind == ModuleLedger.ModuleKind).ToList();
        var platform = owners.Single(owner => owner.Kind == ModuleLedger.PlatformKind);
        var builder = new StringBuilder();

        builder.Append(Header).Append("\n\n");
        builder.Append("`W` is synchronous write coupling and `R` is read or validation coupling. `E` after-commit events and `Q` read-model queries are not syntactically observable, so this file does not report them. `P` is the free Platform hub, `A` is a Platform adapter reach count, and `—` means no live edge.\n\n");
        AppendMatrix(builder, ledger, edges, tables, adapters, modules, platform);
        builder.Append("\n");
        AppendForeignKeys(builder, tables);
        builder.Append("\n");
        AppendDifferences(builder, ledger, edges, tables, adapters, modules, platform);
        return builder.ToString();
    }

    public static IReadOnlySet<(string From, string To)> LiveModulePairs(ModuleLedger ledger,
        ModuleLedgerReport edges)
    {
        var kinds = ledger.Owners.ToDictionary(owner => owner.Name, owner => owner.Kind, StringComparer.Ordinal);
        return edges.LiveEdges.Where(edge => kinds.GetValueOrDefault(edge.From) == ModuleLedger.ModuleKind
                && kinds.GetValueOrDefault(edge.To) == ModuleLedger.ModuleKind)
            .Select(edge => (edge.From, edge.To)).ToHashSet();
    }

    private static IReadOnlyList<OwnerDefinition> OrderedOwners(ModuleLedger ledger) => ledger.Owners
        .Where(owner => owner.Kind == ModuleLedger.ModuleKind)
        .Concat(ledger.Owners.Where(owner => owner.Kind == ModuleLedger.PlatformKind))
        .ToList();

    private static void AppendMatrix(StringBuilder builder, ModuleLedger ledger, ModuleLedgerReport edges,
        TableOwnerReport tables, AdapterReachReport adapters, IReadOnlyList<OwnerDefinition> modules,
        OwnerDefinition platform)
    {
        builder.Append("| from / to");
        foreach (var owner in modules.Append(platform))
        {
            builder.Append(" | ").Append(owner.Name);
        }
        builder.Append(" |\n|---");
        foreach (var _ in modules.Append(platform))
        {
            builder.Append("|---:");
        }
        builder.Append("|\n");

        foreach (var row in modules.Append(platform))
        {
            builder.Append("| ").Append(row.Name);
            foreach (var column in modules.Append(platform))
            {
                builder.Append(" | ").Append(GeneratedCell(ledger, edges, tables, adapters, row.Name, column.Name,
                    platform.Name));
            }
            builder.Append(" |\n");
        }
    }

    private static string GeneratedCell(ModuleLedger ledger, ModuleLedgerReport edges, TableOwnerReport tables,
        AdapterReachReport adapters, string from, string to, string platform)
    {
        if (from == platform)
        {
            return to == platform ? "—" : AdapterCell(adapters, to);
        }
        if (to == platform)
        {
            return "P";
        }
        return ModuleCell(ledger, edges, tables, from, to);
    }

    private static string AdapterCell(AdapterReachReport adapters, string owner)
    {
        var count = adapters.LiveReach.Where(reach => reach.Owner == owner)
            .Select(reach => reach.Symbol).Distinct(StringComparer.Ordinal).Count();
        return count == 0 ? "—" : $"A ({count})";
    }

    private static string ModuleCell(ModuleLedger ledger, ModuleLedgerReport edges, TableOwnerReport tables,
        string from, string to)
    {
        var live = edges.LiveEdges.Where(edge => edge.From == from && edge.To == to).ToList();
        if (live.Count == 0)
        {
            return "—";
        }

        var kind = ledger.Edges.Single(cell => cell.From == from && cell.To == to).Kind;
        var symbols = live.Select(edge => edge.Symbol).Distinct(StringComparer.Ordinal).Count();
        var foreignKeys = tables.CrossOwnerForeignKeys.Count(foreignKey => foreignKey.From == from && foreignKey.To == to);
        return foreignKeys == 0 ? $"{kind} ({symbols})" : $"{kind} ({symbols}) fk:{foreignKeys}";
    }

    private static void AppendForeignKeys(StringBuilder builder, TableOwnerReport tables)
    {
        builder.Append("## Cross-owner foreign keys\n\n");
        builder.Append("| name | table | from | to |\n|---|---|---|---|\n");
        foreach (var foreignKey in tables.CrossOwnerForeignKeys)
        {
            builder.Append("| ").Append(foreignKey.Name).Append(" | ").Append(foreignKey.Table)
                .Append(" | ").Append(foreignKey.From).Append(" | ").Append(foreignKey.To).Append(" |\n");
        }
    }

    private static void AppendDifferences(StringBuilder builder, ModuleLedger ledger, ModuleLedgerReport edges,
        TableOwnerReport tables, AdapterReachReport adapters, IReadOnlyList<OwnerDefinition> modules,
        OwnerDefinition platform)
    {
        var ownerNames = modules.Append(platform).Select(owner => owner.Name).ToHashSet(StringComparer.Ordinal);
        var cells = HandWrittenCells().Where(cell => ownerNames.Contains(GeneratedOwner(cell.From, platform.Name))
                && ownerNames.Contains(cell.To))
            .Select(cell => cell with
            {
                Generated = GeneratedCell(ledger, edges, tables, adapters, GeneratedOwner(cell.From, platform.Name),
                    cell.To, platform.Name),
            }).ToList();
        var observable = cells.Where(cell => cell.HandWritten is "W" or "R" or "—"
                && KindOf(cell.Generated) is "W" or "R" or "—"
                && KindOf(cell.Generated) != cell.HandWritten);
        var unobservable = cells.Where(cell => cell.HandWritten is "E" or "Q/P" || cell.From == "Platform/adapters");

        builder.Append("## Observable differences\n\n");
        builder.Append("| from | to | hand-written | generated |\n|---|---|---|---|\n");
        AppendDifferenceRows(builder, observable);
        builder.Append("\n## Cells the generator cannot observe\n\n");
        builder.Append("After-commit events and read-model queries are not syntactically observable, and Platform is the free hub, so these cells show the generator's structural output instead.\n\n");
        builder.Append("| from | to | hand-written | generated |\n|---|---|---|---|\n");
        AppendDifferenceRows(builder, unobservable);
    }

    private static IEnumerable<HandWrittenCell> HandWrittenCells() => HandWrittenMatrix.SelectMany(row =>
        row.Cells.Select((cell, index) => new HandWrittenCell(row.From, HandWrittenColumns[index], cell, string.Empty)));

    private static void AppendDifferenceRows(StringBuilder builder, IEnumerable<HandWrittenCell> cells)
    {
        foreach (var cell in cells)
        {
            builder.Append("| ").Append(cell.From).Append(" | ").Append(cell.To).Append(" | ")
                .Append(cell.HandWritten).Append(" | ").Append(cell.Generated).Append(" |\n");
        }
    }

    private static string GeneratedOwner(string owner, string platform) => owner == "Platform/adapters" ? platform : owner;

    private static string KindOf(string cell) => cell == "—" ? cell : cell[..1];

    private sealed record HandWrittenCell(string From, string To, string HandWritten, string Generated);
}
