namespace Cluckwork.Application.Tests.Architecture;

internal static partial class RealModuleLedger
{
    internal static readonly AdapterRoots AdapterRoots = new(
        [
            "Cluckwork.Api.Endpoints",
            "Cluckwork.Api.Modules",
            "Cluckwork.Api.Cli",
            "Cluckwork.Infrastructure.Jobs",
        ],
        [
            "Cluckwork.Infrastructure.Persistence.DemoDataSeeder",
            "Cluckwork.Infrastructure.Persistence.SimulationDataSeeder",
        ])
    {
        TopLevelPrograms = ["Cluckwork.Api"],
        PersistenceForbiddenNamespaces = ["Cluckwork.Api.Endpoints", "Cluckwork.Api.Modules"],
    };

    internal static readonly AdapterClaim[] Adapters =
    [
        new("Cluckwork.Api.Cli.BootstrapAdminCliCommand.RunAsync", ["Access"]),
        new("Cluckwork.Api.Cli.ListAccountsCliCommand.RunAsync", ["Farm"]),
        new("Cluckwork.Api.Cli.ProvisionAccountCliCommand.RunAsync", ["Access"]),
        new("Cluckwork.Api.Cli.ReactivateAccountCliCommand.RunAsync", [
            "Access",
            "Farm",
        ]),
        new("Cluckwork.Api.Cli.RecoverAdminCliCommand.RunAsync", ["Access"]),
        new("Cluckwork.Api.Cli.RenameAccountCliCommand.RunAsync", [
            "Access",
            "Farm",
        ]),
        new("Cluckwork.Api.Cli.SeedCliCommand.RunAsync", ["Farm"]),
        new("Cluckwork.Api.Cli.SuspendAccountCliCommand.RunAsync", [
            "Access",
            "Farm",
        ]),
        new("Cluckwork.Api.Modules.Farm.Accounts.AccountEndpoints.GetAccount", ["Farm"]),
        new("Cluckwork.Api.Modules.Farm.Accounts.AccountEndpoints.GetSettings", ["Farm"]),
        new("Cluckwork.Api.Modules.Farm.Accounts.AccountEndpoints.ShowFarmWideSaleAllocationNotice", ["Farm"]),
        new("Cluckwork.Api.Modules.Farm.Accounts.AccountEndpoints.ToResponse", ["Farm"]),
        new("Cluckwork.Api.Modules.Farm.Accounts.AccountEndpoints.UpdateSettings", ["Farm"]),
        new("Cluckwork.Api.Modules.Farm.Accounts.AccountEndpoints.YourMaxDiscountPercent", ["Farm"]),
        new("Cluckwork.Api.Modules.Farm.Accounts.FarmBannerEndpoints.GetBanner", ["Farm"]),
        new("Cluckwork.Api.Modules.Farm.Accounts.FarmBannerEndpoints.RemoveBanner", ["Farm"]),
        new("Cluckwork.Api.Modules.Farm.Accounts.FarmBannerEndpoints.SetBanner", ["Farm"]),
        new("Cluckwork.Api.Modules.Farm.Accounts.FarmBannerEndpoints.ToResponse", ["Farm"]),
        new("Cluckwork.Api.Modules.Farm.Accounts.FarmLogoEndpoints.GetLogo", ["Farm"]),
        new("Cluckwork.Api.Modules.Farm.Accounts.FarmLogoEndpoints.RemoveLogo", ["Farm"]),
        new("Cluckwork.Api.Modules.Farm.Accounts.FarmLogoEndpoints.SetLogo", ["Farm"]),
        new("Cluckwork.Api.Modules.Farm.Accounts.FarmLogoEndpoints.ToResponse", ["Farm"]),
        new("Cluckwork.Api.Modules.Insights.Audit.AuditEndpoints.ListAuditEvents", ["Insights"]),
        new("Cluckwork.Api.Modules.Access.Auth.AuthEndpoints.ChangePassword", ["Access"]),
        new("Cluckwork.Api.Modules.Access.Auth.AuthEndpoints.Login", ["Access"]),
        new("Cluckwork.Api.Modules.Access.Auth.AuthEndpoints.Logout", ["Access"]),
        new("Cluckwork.Api.Modules.Access.Auth.AuthEndpoints.Refresh", ["Access"]),
        new("Cluckwork.Api.Modules.Access.Auth.AuthEndpoints.StepUp", ["Access"]),
        new("Cluckwork.Api.Modules.Commerce.Catalog.ProductEndpoints.CreateProduct", ["Commerce"]),
        new("Cluckwork.Api.Modules.Commerce.Catalog.ProductEndpoints.ListConversions", ["Commerce"]),
        new("Cluckwork.Api.Modules.Commerce.Catalog.ProductEndpoints.ListProducts", ["Commerce"]),
        new("Cluckwork.Api.Modules.Commerce.Catalog.ProductEndpoints.MapProductEndpoints", ["Commerce"]),
        new("Cluckwork.Api.Modules.Commerce.Catalog.ProductEndpoints.SetActive", ["Commerce"]),
        new("Cluckwork.Api.Modules.Commerce.Catalog.ProductEndpoints.ToResponse", ["Commerce"]),
        new("Cluckwork.Api.Modules.Commerce.Catalog.ProductEndpoints.UpdateConversion", ["Commerce"]),
        new("Cluckwork.Api.Modules.Commerce.Catalog.ProductEndpoints.UpdateProduct", ["Commerce"]),
        new("Cluckwork.Api.Modules.Commerce.Customers.CustomerEndpoints.CreateCustomer", ["Commerce"]),
        new("Cluckwork.Api.Modules.Commerce.Customers.CustomerEndpoints.GetCustomer", ["Commerce"]),
        new("Cluckwork.Api.Modules.Commerce.Customers.CustomerEndpoints.ListCustomers", ["Commerce"]),
        new("Cluckwork.Api.Modules.Commerce.Customers.CustomerEndpoints.ToResponse", ["Commerce"]),
        new("Cluckwork.Api.Modules.Commerce.Customers.CustomerEndpoints.UpdateCustomer", ["Commerce"]),
        new("Cluckwork.Api.Modules.EggOperations.DailyEntries.DailyEntryEndpoints.AdjustDailyEntry", ["EggOperations"]),
        new("Cluckwork.Api.Modules.EggOperations.DailyEntries.DailyEntryEndpoints.GetDailyEntry", [
            "EggOperations",
            "FlockManagement",
            "Insights",
        ]),
        new("Cluckwork.Api.Modules.EggOperations.DailyEntries.DailyEntryEndpoints.ListDailyEntries", [
            "EggOperations",
            "FlockManagement",
            "Insights",
        ]),
        new("Cluckwork.Api.Modules.EggOperations.DailyEntries.DailyEntryEndpoints.RecordDailyEntry", ["EggOperations"]),
        new("Cluckwork.Api.Modules.EggOperations.DailyEntries.DailyEntryEndpoints.SubmitDailyEntry", ["EggOperations"]),
        new("Cluckwork.Api.Modules.EggOperations.DailyEntries.DailyEntryEndpoints.ToResponse", [
            "EggOperations",
            "FlockManagement",
            "Insights",
        ]),
        new("Cluckwork.Api.Modules.EggOperations.DailyEntries.DailyEntryEndpoints.VoidDailyEntry", ["EggOperations"]),
        new("Cluckwork.Api.Modules.EggOperations.EggGrades.EggGradeEndpoints.CreateEggGrade", ["EggOperations"]),
        new("Cluckwork.Api.Modules.EggOperations.EggGrades.EggGradeEndpoints.GetEggGrade", [
            "EggOperations",
            "Insights",
        ]),
        new("Cluckwork.Api.Modules.EggOperations.EggGrades.EggGradeEndpoints.ListEggGrades", [
            "EggOperations",
            "Insights",
        ]),
        new("Cluckwork.Api.Modules.EggOperations.EggGrades.EggGradeEndpoints.MapEggGradeEndpoints", ["EggOperations"]),
        new("Cluckwork.Api.Modules.EggOperations.EggGrades.EggGradeEndpoints.SetActive", ["EggOperations"]),
        new("Cluckwork.Api.Modules.EggOperations.EggGrades.EggGradeEndpoints.ToResponse", [
            "EggOperations",
            "Insights",
        ]),
        new("Cluckwork.Api.Modules.EggOperations.EggGrades.EggGradeEndpoints.UpdateEggGrade", ["EggOperations"]),
        new("Cluckwork.Api.Modules.Finance.Expenses.ExpenseEndpoints.AdjustExpense", [
            "Finance",
            "FlockManagement",
            "Insights",
        ]),
        new("Cluckwork.Api.Modules.Finance.Expenses.ExpenseEndpoints.CreateCategory", ["Finance"]),
        new("Cluckwork.Api.Modules.Finance.Expenses.ExpenseEndpoints.CreateExpense", ["Finance"]),
        new("Cluckwork.Api.Modules.Finance.Expenses.ExpenseEndpoints.FlockNameAsync", ["FlockManagement"]),
        new("Cluckwork.Api.Modules.Finance.Expenses.ExpenseEndpoints.GetExpense", [
            "Finance",
            "FlockManagement",
            "Insights",
        ]),
        new("Cluckwork.Api.Modules.Finance.Expenses.ExpenseEndpoints.ListCategories", ["Finance"]),
        new("Cluckwork.Api.Modules.Finance.Expenses.ExpenseEndpoints.ListExpenses", [
            "Farm",
            "Finance",
            "FlockManagement",
            "Insights",
        ]),
        new("Cluckwork.Api.Modules.Finance.Expenses.ExpenseEndpoints.ToResponse", [
            "Finance",
            "Insights",
        ]),
        new("Cluckwork.Api.Modules.Finance.Expenses.ExpenseEndpoints.UpdateCategory", ["Finance"]),
        new("Cluckwork.Api.Modules.Insights.Export.CsvExport.WriteAsync", ["Insights"]),
        new("Cluckwork.Api.Modules.Insights.Export.ExportEndpoints.ExportAll", ["Insights"]),
        new("Cluckwork.Api.Modules.Insights.Export.ExportEndpoints.ExportDataset", ["Insights"]),
        new("Cluckwork.Api.Modules.Insights.Export.ExportEndpoints.WriteZipAsync", ["Insights"]),
        new("Cluckwork.Api.Modules.FlockManagement.Flocks.FlockEndpoints.ArchiveFlock", ["FlockManagement"]),
        new("Cluckwork.Api.Modules.FlockManagement.Flocks.FlockEndpoints.CreateFlock", ["FlockManagement"]),
        new("Cluckwork.Api.Modules.FlockManagement.Flocks.FlockEndpoints.DepleteFlock", ["FlockManagement"]),
        new("Cluckwork.Api.Modules.FlockManagement.Flocks.FlockEndpoints.GetFlock", [
            "FlockManagement",
            "Insights",
        ]),
        new("Cluckwork.Api.Modules.FlockManagement.Flocks.FlockEndpoints.ListFlocks", [
            "FlockManagement",
            "Insights",
        ]),
        new("Cluckwork.Api.Modules.FlockManagement.Flocks.FlockEndpoints.ListMovements", ["FlockManagement"]),
        new("Cluckwork.Api.Modules.FlockManagement.Flocks.FlockEndpoints.ReactivateFlock", ["FlockManagement"]),
        new("Cluckwork.Api.Modules.FlockManagement.Flocks.FlockEndpoints.RecordMovement", ["FlockManagement"]),
        new("Cluckwork.Api.Modules.FlockManagement.Flocks.FlockEndpoints.ToResponse", [
            "FlockManagement",
            "Insights",
        ]),
        new("Cluckwork.Api.Modules.FlockManagement.Flocks.FlockEndpoints.UpdateFlock", ["FlockManagement"]),
        new("Cluckwork.Api.Modules.GeneralInventory.Inventory.InventoryEndpoints.CreateItem", ["GeneralInventory"]),
        new("Cluckwork.Api.Modules.GeneralInventory.Inventory.InventoryEndpoints.GetItem", ["GeneralInventory"]),
        new("Cluckwork.Api.Modules.GeneralInventory.Inventory.InventoryEndpoints.ListFeedUsage", [
            "FlockManagement",
            "GeneralInventory",
        ]),
        new("Cluckwork.Api.Modules.GeneralInventory.Inventory.InventoryEndpoints.ListItems", ["GeneralInventory"]),
        new("Cluckwork.Api.Modules.GeneralInventory.Inventory.InventoryEndpoints.ListLots", ["GeneralInventory"]),
        new("Cluckwork.Api.Modules.GeneralInventory.Inventory.InventoryEndpoints.ListMovements", ["GeneralInventory"]),
        new("Cluckwork.Api.Modules.GeneralInventory.Inventory.InventoryEndpoints.MapInventoryEndpoints", ["GeneralInventory"]),
        new("Cluckwork.Api.Modules.GeneralInventory.Inventory.InventoryEndpoints.RecordAdjustment", ["GeneralInventory"]),
        new("Cluckwork.Api.Modules.GeneralInventory.Inventory.InventoryEndpoints.RecordFeedUsage", ["GeneralInventory"]),
        new("Cluckwork.Api.Modules.GeneralInventory.Inventory.InventoryEndpoints.RecordPurchase", ["GeneralInventory"]),
        new("Cluckwork.Api.Modules.GeneralInventory.Inventory.InventoryEndpoints.SetActive", ["GeneralInventory"]),
        new("Cluckwork.Api.Modules.GeneralInventory.Inventory.InventoryEndpoints.ToResponse", ["GeneralInventory"]),
        new("Cluckwork.Api.Modules.GeneralInventory.Inventory.InventoryEndpoints.UpdateItem", ["GeneralInventory"]),
        new("Cluckwork.Api.Modules.Access.Me.MeEndpoints.GetMe", ["Access"]),
        new("Cluckwork.Api.Modules.Access.Me.MeEndpoints.SetLanguage", ["Access"]),
        new("Cluckwork.Api.Modules.Access.Me.MeEndpoints.SetStepperUnit", ["Access"]),
        new("Cluckwork.Api.Modules.Insights.Reports.ReportEndpoints.Expenses", ["Insights"]),
        new("Cluckwork.Api.Modules.Insights.Reports.ReportEndpoints.Production", [
            "FlockManagement",
            "Insights",
        ]),
        new("Cluckwork.Api.Modules.Insights.Reports.ReportEndpoints.Profit", ["Insights"]),
        new("Cluckwork.Api.Modules.Insights.Reports.ReportEndpoints.Sales", ["Insights"]),
        new("Cluckwork.Api.Modules.Commerce.Sales.PaymentEndpoints.ListCustomerBalances", [
            "Commerce",
            "Farm",
        ]),
        new("Cluckwork.Api.Modules.Commerce.Sales.PaymentEndpoints.ListOrderPayments", ["Commerce"]),
        new("Cluckwork.Api.Modules.Commerce.Sales.PaymentEndpoints.RecordPayment", ["Commerce"]),
        new("Cluckwork.Api.Modules.Commerce.Sales.PaymentEndpoints.ToResponse", ["Commerce"]),
        new("Cluckwork.Api.Modules.Commerce.Sales.PaymentEndpoints.VoidPayment", ["Commerce"]),
        new("Cluckwork.Api.Modules.Commerce.Sales.SaleEndpoints.AddOrderItem", ["Commerce"]),
        new("Cluckwork.Api.Modules.Commerce.Sales.SaleEndpoints.CancelSalesOrder", ["Commerce"]),
        new("Cluckwork.Api.Modules.Commerce.Sales.SaleEndpoints.ConfirmSale", ["Commerce"]),
        new("Cluckwork.Api.Modules.Commerce.Sales.SaleEndpoints.CreateSalesOrder", ["Commerce"]),
        new("Cluckwork.Api.Modules.Commerce.Sales.SaleEndpoints.GetSalesOrder", [
            "Commerce",
            "EggOperations",
            "Insights",
        ]),
        new("Cluckwork.Api.Modules.Commerce.Sales.SaleEndpoints.ListSalesOrders", [
            "Commerce",
            "EggOperations",
            "Insights",
        ]),
        new("Cluckwork.Api.Modules.Commerce.Sales.SaleEndpoints.RemoveOrderItem", ["Commerce"]),
        new("Cluckwork.Api.Modules.Commerce.Sales.SaleEndpoints.ToResponse", [
            "Commerce",
            "Insights",
        ]),
        new("Cluckwork.Api.Modules.Commerce.Sales.SaleEndpoints.UpdateOrderItem", ["Commerce"]),
        new("Cluckwork.Api.Modules.Commerce.Sales.SaleEndpoints.VoidSale", ["Commerce"]),
        new("Cluckwork.Api.Modules.EggOperations.Stock.StockEndpoints.GetStock", ["EggOperations"]),
        new("Cluckwork.Api.Modules.EggOperations.Stock.StockEndpoints.ListLotMovements", ["EggOperations"]),
        new("Cluckwork.Api.Modules.EggOperations.Stock.StockEndpoints.ListLots", ["EggOperations"]),
        new("Cluckwork.Api.Modules.EggOperations.Stock.StockEndpoints.RecordLotMovement", ["EggOperations"]),
        new("Cluckwork.Api.Modules.Access.Users.UserEndpoints.AssignFlock", ["Access"]),
        new("Cluckwork.Api.Modules.Access.Users.UserEndpoints.ChangeUserEmail", ["Access"]),
        new("Cluckwork.Api.Modules.Access.Users.UserEndpoints.ChangeUserRole", ["Access"]),
        new("Cluckwork.Api.Modules.Access.Users.UserEndpoints.CreateUser", ["Access"]),
        new("Cluckwork.Api.Modules.Access.Users.UserEndpoints.DisableUser", ["Access"]),
        new("Cluckwork.Api.Modules.Access.Users.UserEndpoints.EnableUser", ["Access"]),
        new("Cluckwork.Api.Modules.Access.Users.UserEndpoints.ListAssignments", ["Access"]),
        new("Cluckwork.Api.Modules.Access.Users.UserEndpoints.ListUsers", ["Access"]),
        new("Cluckwork.Api.Modules.Access.Users.UserEndpoints.SetUserPassword", ["Access"]),
        new("Cluckwork.Api.Modules.Access.Users.UserEndpoints.UnassignFlock", ["Access"]),
        new("Cluckwork.Api.Modules.Access.Users.UserEndpoints.UpdateUser", ["Access"]),
        new("Cluckwork.Api.Modules.GeneralInventory.Water.WaterUsageEndpoints.ListWaterUsage", [
            "FlockManagement",
            "GeneralInventory",
        ]),
        new("Cluckwork.Api.Modules.GeneralInventory.Water.WaterUsageEndpoints.RecordWaterUsage", ["GeneralInventory"]),
        new("Cluckwork.Api.Modules.GeneralInventory.Water.WaterUsageEndpoints.UpdateWaterUsage", ["GeneralInventory"]),
        new("Cluckwork.Infrastructure.Jobs.DailyEntryLockSweep.LockDueEntriesAsync", ["EggOperations"]),
        new("Cluckwork.Infrastructure.Jobs.DailyEntryLockSweep.RunAsync", ["Farm"]),
        new("Cluckwork.Infrastructure.Jobs.RefreshTokenPurgeSweep.RunAsync", ["Access"]),
        new("Cluckwork.Infrastructure.Persistence.DemoDataSeeder.Require", ["EggOperations"]),
        new("Cluckwork.Infrastructure.Persistence.DemoDataSeeder.ctor", [
            "Access",
            "Commerce",
            "EggOperations",
            "Farm",
            "FlockManagement",
        ]),
        new("Cluckwork.Infrastructure.Persistence.SimulationDataSeeder.Require", [
            "Commerce",
            "EggOperations",
            "GeneralInventory",
        ]),
        new("Cluckwork.Infrastructure.Persistence.SimulationDataSeeder.SeedSecondAccountAsync", ["Farm"]),
        new("Cluckwork.Infrastructure.Persistence.SimulationDataSeeder.TransitionFlockAsync", ["FlockManagement"]),
        new("Cluckwork.Infrastructure.Persistence.SimulationDataSeeder.ctor", [
            "Access",
            "Commerce",
            "EggOperations",
            "Farm",
            "Finance",
            "FlockManagement",
            "GeneralInventory",
        ]),
    ];

    internal static readonly AdapterTier[] AdapterTiers =
    [
        new("Cluckwork.Api.Mcp",
            "DirectRepository",
            "MapMcp",
            "MCP tool classes inject repositories by design (docs/plans/770-mcp-server/01-design.md:112); the contract-first shape is Track C (#514)",
            "#806"),
    ];
}
