namespace Cluckwork.Application.Tests.Architecture;

internal static partial class RealModuleLedger
{
    internal static readonly ForeignKeyCell[] ForeignKeys =
    [
        new("AspNetUsers",
            "FK_AspNetUsers_Accounts_AccountId",
            "Access",
            "Farm",
            "a user belongs to a farm; AccountProvisioner establishes the account membership (design 3.3)"),
        new("BirdMovements",
            "FK_BirdMovements_DailyEntries_DailyEntryId",
            "FlockManagement",
            "EggOperations",
            "mortality movements retain daily-entry provenance; daily-entry handlers append through Flock Management's IMortalityLedger port (#852). BirdMovementConfiguration, which declares this constraint, is the only Flock Management code that references Egg Operations, through the FlockManagement -> EggOperations edge cell (#1087 S9); the constraint stays schema-only (design 3.3)"),
        new("Expenses",
            "FK_Expenses_Flocks_FlockId",
            "Finance",
            "FlockManagement",
            "an expense may be attributed to a flock; validated through IFlockRepository (design 3.3)"),
        new("FeedUsages",
            "FK_FeedUsages_DailyEntries_DailyEntryId",
            "GeneralInventory",
            "EggOperations",
            "feed usage retains daily-entry provenance; resolved through IDailyEntryLookup (#853, design 3.3)"),
        new("FeedUsages",
            "FK_FeedUsages_Flocks_FlockId",
            "GeneralInventory",
            "FlockManagement",
            "feed usage belongs to a flock; validated through IFlockRepository (design 3.3)"),
        new("InventoryMovements",
            "FK_InventoryMovements_Flocks_FlockId",
            "GeneralInventory",
            "FlockManagement",
            "inventory movements may be attributed to a flock; the constraint preserves that reference (design 3.3)"),
        new("ProductEggGradeMappings",
            "FK_ProductEggGradeMappings_EggGrades_EggGradeId",
            "Commerce",
            "EggOperations",
            "product grade mappings reference egg grades; catalog handlers validate through IEggGradeLookup (#854, design 3.3)"),
        new("SalesOrderAllocations",
            "FK_SalesOrderAllocations_EggLots_EggLotId",
            "Commerce",
            "EggOperations",
            "sale allocations reserve egg lots; ConfirmSaleHandler allocates through IEggStock (#854, design 3.3)"),
        new("SalesOrderItems",
            "FK_SalesOrderItems_EggGrades_EggGradeId",
            "Commerce",
            "EggOperations",
            "sale items retain their egg grade; AddOrderItemHandler validates through IEggGradeLookup (#854, design 3.3)"),
        new("WaterUsages",
            "FK_WaterUsages_DailyEntries_DailyEntryId",
            "GeneralInventory",
            "EggOperations",
            "water usage retains daily-entry provenance; resolved through IDailyEntryLookup (#853, design 3.3)"),
        new("WaterUsages",
            "FK_WaterUsages_Flocks_FlockId",
            "GeneralInventory",
            "FlockManagement",
            "water usage belongs to a flock; validated through IFlockRepository (design 3.3)"),
    ];

    internal static readonly TableOwnerOverride[] TableOwnerOverrides =
    [
        new("AspNetRoleClaims", "Access",
            "Design 3.3 assigns Identity claim, join and token tables to Access; this framework CLR namespace is outside the Cluckwork namespace owner map."),
        new("AspNetUserClaims", "Access",
            "Design 3.3 assigns Identity claim, join and token tables to Access; this framework CLR namespace is outside the Cluckwork namespace owner map."),
        new("AspNetUserLogins", "Access",
            "Design 3.3 assigns Identity claim, join and token tables to Access; this framework CLR namespace is outside the Cluckwork namespace owner map."),
        new("AspNetUserRoles", "Access",
            "Design 3.3 assigns Identity claim, join and token tables to Access; this framework CLR namespace is outside the Cluckwork namespace owner map."),
        new("AspNetUserTokens", "Access",
            "Design 3.3 assigns Identity claim, join and token tables to Access; this framework CLR namespace is outside the Cluckwork namespace owner map."),
        new("AuditEvents", "Platform",
            "Every module's handlers write audit events through IAuditWriter; Platform owns the shared trail (#500, #508)."),
        new("durable_jobs", "Platform",
            "The durable job queue behind DurableJobWorker serves every module's background work (#271)."),
        new("idempotency_records", "Platform",
            "The HTTP idempotency middleware claims and replays writes for every endpoint (#307)."),
        new("simulation_seed_state", "Platform",
            "The simulation seed's per-account bookmark belongs to the seed verb, not to a module (#279)."),
        new("UserRoleAssignments", "Access",
            "Design 3.3 assigns flock role assignments to Access; the CLR type remains in Cluckwork.Domain.Modules.Farm.Accounts, owned by Farm. No namespace move is authorized by this ledger."),
    ];
}
