namespace Cluckwork.Application.Tests.Architecture;

internal static partial class RealModuleLedger
{
    internal static readonly EdgeCell[] Edges =
    [
        new("Access", "Commerce", "W",
            "W because AccountProvisioner inserts EggUnitConversion.Defaults for a new farm inside its provisioning transaction; the rest of the cell reads. Identity carries the per-user stepper-unit preference: ApplicationUser stores Domain.Catalog.EggUnit, IdentityProvider reads and writes it, SetStepperUnitHandler resolves it through Commerce's IEggUnitConversionLookup port (#854) and rejects inactive conversions, and SetStepperUnitValidator validates only the enum name. Nothing prevents a stored preference from pointing at a conversion later deactivated through UpdateEggUnitConversionHandler. Design 3.4 shows Access -> Commerce as none; this is live coupling the target design has still to remove.",
            [
                "Cluckwork.Application.Features.Users.SetStepperUnit.SetStepperUnitHandler",
                "Cluckwork.Application.Features.Users.SetStepperUnit.SetStepperUnitValidator",
                "Cluckwork.Infrastructure.Identity.AccountProvisioner",
                "Cluckwork.Infrastructure.Identity.ApplicationUser",
                "Cluckwork.Infrastructure.Identity.IdentityProvider",
            ]),
        new("Access", "EggOperations", "W",
            "W because AccountProvisioner inserts a new farm's default grades, Domain.Eggs.EggGrade.Defaults(accountId, SeedDefaults.FarmId), inside its provisioning transaction, so farm provisioning writes Egg Operations' table and depends on its grade shape. Design 3.4 shows Access -> Egg Ops as none; this is live coupling the target design has still to remove.",
            ["Cluckwork.Infrastructure.Identity.AccountProvisioner"]),
        new("Access", "Farm", "W",
            "W because AccountProvisioner inserts the new Account inside its provisioning transaction and AccountRenameService calls Account.Rename and saves; the rest of the cell reads. Identity is where a farm is created, renamed, suspended and recovered. AccountProvisioner, AccountRenameService, AccountSuspensionService, AdminRecoveryService, FirstRunAdminService and FirstRunStatusService load Domain.Accounts.Account or inject Farm's IAccountRepository, and IdentityProvider takes that repository by fully qualified name for the account-scoped login (#532). CredentialEpochVerifier reads Account.IsActive in the same fresh per-request query as the user's credential epoch, so a suspended farm's credentials stop working at once (#364, #579, #857). The user validators read Domain.Accounts.Roles for the assignable role set, and IUserRoleAssignmentRepository returns Domain.Accounts.UserRoleAssignment rows. IAccessLookup returns Domain.Accounts.EffectiveAccountRole, and AccessLookup resolves it with Roles.ResolveEffective in its private effective-role routine (#612, #857). Design 3.4 row Access -> Farm = R. AccessFixture (#858) creates the simulation fixture's UserRoleAssignment through the scoped context, and AccessSeedLookup checks the fixture's Owner role by Roles.Owner.",
            [
                "Cluckwork.Application.Features.Users.AssignFlock.AssignFlockHandler",
                "Cluckwork.Application.Features.Users.AssignFlock.UnassignFlockHandler",
                "Cluckwork.Application.Features.Users.ChangeUserRole.ChangeUserRoleValidator",
                "Cluckwork.Application.Features.Users.CreateUser.CreateUserValidator",
                "Cluckwork.Application.Features.Users.IAccessLookup",
                "Cluckwork.Application.Features.Users.IUserRoleAssignmentRepository",
                "Cluckwork.Application.Features.Users.UserFlockAssignment",
                "Cluckwork.Infrastructure.Identity.AccessFixture",
                "Cluckwork.Infrastructure.Identity.AccessLookup",
                "Cluckwork.Infrastructure.Identity.AccessSeedLookup",
                "Cluckwork.Infrastructure.Identity.AccountProvisioner",
                "Cluckwork.Infrastructure.Identity.AccountRenameService",
                "Cluckwork.Infrastructure.Identity.AccountSuspensionService",
                "Cluckwork.Infrastructure.Identity.AdminRecoveryService",
                "Cluckwork.Infrastructure.Identity.CredentialEpochVerifier",
                "Cluckwork.Infrastructure.Identity.FirstRunAdminService",
                "Cluckwork.Infrastructure.Identity.FirstRunProvisioningLatch",
                "Cluckwork.Infrastructure.Identity.FirstRunStatusService",
                "Cluckwork.Infrastructure.Identity.IdentityProvider",
            ]),
        new("Access", "FlockManagement", "R",
            "AssignFlockHandler injects Flock Management's IFlockLookup port to prove the flock exists before narrowing a worker to it and to name it in the audit row (#103, spec 5.2/5.3); UnassignFlockHandler shares its file and namespace imports. Design 3.4 row Access -> Flock = R. AccessFixture (#858) reads the same port for the simulation fixture's assignment and audit row.",
            [
                "Cluckwork.Application.Features.Users.AssignFlock.AssignFlockHandler",
                "Cluckwork.Application.Features.Users.AssignFlock.UnassignFlockHandler",
                "Cluckwork.Infrastructure.Identity.AccessFixture",
            ]),
        new("Commerce", "Access", "R",
            "ConfirmSaleHandler reads through Access's IAccessLookup port (GetEffectiveRoleAsync and GetAssignedFlocksAsync, #857) inside the confirm transaction, so a plain Worker's committed flock assignments and the discount ceiling bound to their effective role are read at the moment of confirmation rather than from a request-start snapshot (#727). Design 3.4 shows Commerce -> Access as none; this is live coupling the target design has still to remove.",
            ["Cluckwork.Application.Features.Sales.ConfirmSale.ConfirmSaleHandler"]),
        new("Commerce", "EggOperations", "W",
            "FIFO egg stock. ConfirmSaleHandler and VoidSaleHandler lock, draw from and return egg lots through Egg Operations' IEggStock port, which adds the lot changes and Sale or Void movements to the confirm and void transactions and never saves (#854); Commerce sees plans and lot ids, never Domain.Eggs.EggLot. Products, order lines and confirm refusals read grades through IEggGradeLookup in CreateProductHandler, UpdateProductHandler, AddOrderItemHandler and ConfirmSaleHandler. Design 3.4 row Commerce -> Egg Ops = W.",
            [
                "Cluckwork.Application.Features.Catalog.CreateProduct.CreateProductHandler",
                "Cluckwork.Application.Features.Catalog.UpdateProduct.UpdateProductHandler",
                "Cluckwork.Application.Features.Sales.AddOrderItem.AddOrderItemHandler",
                "Cluckwork.Application.Features.Sales.ConfirmSale.ConfirmSaleHandler",
                "Cluckwork.Application.Features.Sales.VoidSale.VoidSaleHandler",
            ]),
        new("Commerce", "Farm", "R",
            "Orders and products snapshot the farm's currency through Farm's IAccountRepository (CreateSalesOrderHandler, CreateProductHandler, UpdateProductHandler), with the sales-order path holding the FOR SHARE lock on the account row (#162) so an order cannot land in a denomination the farm is mid-flight out of; ConfirmSaleHandler also reads the farm's discount ceiling and worker sale-allocation policy off Account. Design 3.4 row Commerce -> Farm = R.",
            [
                "Cluckwork.Application.Features.Catalog.CreateProduct.CreateProductHandler",
                "Cluckwork.Application.Features.Catalog.UpdateProduct.UpdateProductHandler",
                "Cluckwork.Application.Features.Sales.ConfirmSale.ConfirmSaleHandler",
                "Cluckwork.Application.Features.Sales.CreateSalesOrder.CreateSalesOrderHandler",
            ]),
        new("EggOperations", "Farm", "R",
            "CreateEggGradeHandler attaches a new grade to Domain.Accounts.SeedDefaults.FarmId, the single-farm stand-in for the farm the grade belongs to; EggGradeFloorPolicy resolves the caller's effective role through Domain.Accounts.Roles to decide whether a grade's low-stock floor may move (#911, Owner-only per #729). Design 3.4 row Egg Ops -> Farm = R.",
            [
                "Cluckwork.Application.Features.EggGrades.CreateEggGrade.CreateEggGradeHandler",
                "Cluckwork.Application.Features.EggGrades.EggGradeFloorPolicy",
            ]),
        new("EggOperations", "FlockManagement", "W",
            "Daily entry is the mortality writer: SubmitDailyEntryHandler, AdjustDailyEntryHandler and VoidDailyEntryHandler append bird-movement rows through Flock Management's IMortalityLedger port, which adds the row to the caller's unit of work and never saves, so it commits with the entry itself (#54, #69, #852). Every daily-entry handler reads the flock through the IFlockLookup port to check CanRecordProductionOn for the entry's date. Design 3.4 row Egg Ops -> Flock = W.",
            [
                "Cluckwork.Application.Features.DailyEntries.AdjustDailyEntry.AdjustDailyEntryHandler",
                "Cluckwork.Application.Features.DailyEntries.AdjustDailyEntry.AdjustDailyEntryResponse",
                "Cluckwork.Application.Features.DailyEntries.RecordDailyEntry.RecordDailyEntryHandler",
                "Cluckwork.Application.Features.DailyEntries.SubmitDailyEntry.SubmitDailyEntryHandler",
                "Cluckwork.Application.Features.DailyEntries.SubmitDailyEntry.SubmitDailyEntryResponse",
                "Cluckwork.Application.Features.DailyEntries.VoidDailyEntry.VoidDailyEntryHandler",
                "Cluckwork.Application.Features.DailyEntries.VoidDailyEntry.VoidDailyEntryResponse",
            ]),
        new("Farm", "Commerce", "R",
            "Farm settings own three Commerce-shaped values. Domain.Accounts.Account holds Domain.Catalog.EggUnit as the farm's default stepper unit and exposes Domain.Sales.DiscountCeiling, while UpdateFarmSettingsHandler resolves the stepper unit through Commerce's IEggUnitConversionLookup port (#854) and UpdateFarmSettingsValidator parses the ceiling with DiscountCeiling.TryParsePercent (#727). The Farm contract's FarmSettingsDetails, declared beside IFarmModule, carries the same Domain.Catalog.EggUnit stepper unit out to its callers (#851). Design 3.4 shows Farm -> Commerce as none; this is live coupling the target design has still to remove.",
            [
                "Cluckwork.Application.Features.Accounts.FarmSettingsDetails",
                "Cluckwork.Application.Features.Accounts.IFarmModule",
                "Cluckwork.Application.Features.Accounts.UpdateFarmSettings.UpdateFarmSettingsHandler",
                "Cluckwork.Application.Features.Accounts.UpdateFarmSettings.UpdateFarmSettingsValidator",
                "Cluckwork.Domain.Accounts.Account",
            ]),
        new("Finance", "Farm", "R",
            "CreateExpenseHandler injects Farm's IAccountRepository for the lock-aware currency snapshot an expense binds to (#162, FOR SHARE on the account row), and it and CreateExpenseCategoryHandler attach their rows to Domain.Accounts.SeedDefaults.FarmId, whose active categories FinanceModule lists. Design 3.4 classes this cell W, but the code reads Farm state under a shared row lock and mutates nothing there, the same shape 3.4 classes R on Commerce -> Farm and Inventory -> Farm; the ledger records what the code does and notes the disagreement here so #848 regenerates the matrix from this reading.",
            [
                "Cluckwork.Application.Features.Expenses.CreateExpense.CreateExpenseHandler",
                "Cluckwork.Application.Features.Expenses.CreateExpenseCategory.CreateExpenseCategoryHandler",
                "Cluckwork.Application.Features.Expenses.FinanceModule",
            ]),
        new("Finance", "FlockManagement", "R",
            "CreateExpenseHandler and AdjustExpenseHandler inject Flock Management's IFlockLookup port to validate the optional flock an expense is attributed to. Design 3.4 row Finance -> Flock = R.",
            [
                "Cluckwork.Application.Features.Expenses.AdjustExpense.AdjustExpenseHandler",
                "Cluckwork.Application.Features.Expenses.CreateExpense.CreateExpenseHandler",
            ]),
        new("FlockManagement", "Farm", "R",
            "CreateFlockHandler places a new flock on Domain.Accounts.SeedDefaults.FarmId and SeedDefaults.HouseId, the single-farm stand-ins. Design 3.4 row Flock -> Farm = R.",
            ["Cluckwork.Application.Features.Flocks.CreateFlock.CreateFlockHandler"]),
        new("GeneralInventory", "EggOperations", "R",
            "RecordFeedUsageHandler and RecordWaterUsageHandler inject Egg Operations' IDailyEntryLookup port by fully qualified name and call FindIdForFlockScopedWriteAsync (#853), so a feed or water record carries the day's daily-entry provenance. Design 3.4 shows Inventory -> Egg Ops as none; this is live coupling the target design has still to remove.",
            [
                "Cluckwork.Application.Features.Inventory.RecordFeedUsage.RecordFeedUsageHandler",
                "Cluckwork.Application.Features.Inventory.RecordWaterUsage.RecordWaterUsageHandler",
            ]),
        new("GeneralInventory", "Farm", "R",
            "CreateInventoryItemHandler, RecordPurchaseHandler and UpdateInventoryItemHandler inject Farm's IAccountRepository for the farm currency a priced item or a purchase snapshots, under the same FOR SHARE account-row lock as the sales path (#162), and CreateInventoryItemHandler attaches the item to Domain.Accounts.SeedDefaults.FarmId. Design 3.4 row Inventory -> Farm = R.",
            [
                "Cluckwork.Application.Features.Inventory.CreateInventoryItem.CreateInventoryItemHandler",
                "Cluckwork.Application.Features.Inventory.RecordPurchase.RecordPurchaseHandler",
                "Cluckwork.Application.Features.Inventory.UpdateInventoryItem.UpdateInventoryItemHandler",
            ]),
        new("GeneralInventory", "FlockManagement", "R",
            "RecordFeedUsageHandler, RecordWaterUsageHandler and UpdateWaterUsageHandler inject Flock Management's IFlockLookup port to prove the flock being fed or watered exists and is eligible for the usage date. Design 3.4 row Inventory -> Flock = R.",
            [
                "Cluckwork.Application.Features.Inventory.RecordFeedUsage.RecordFeedUsageHandler",
                "Cluckwork.Application.Features.Inventory.RecordWaterUsage.RecordWaterUsageHandler",
                "Cluckwork.Application.Features.Inventory.UpdateWaterUsage.UpdateWaterUsageHandler",
            ]),
        new("Insights", "Commerce", "R",
            "ReportQueries reads confirmed SalesOrders and Payments for sales and profit totals; ExportQueries streams Customers, SalesOrders, SalesOrderItems, SalesOrderAllocations and Payments. Reads compose in C# and never mutate Commerce rows.",
            [
                "Cluckwork.Infrastructure.Insights.ExportQueries",
                "Cluckwork.Infrastructure.Insights.ReportQueries",
            ]),
        new("Insights", "EggOperations", "R",
            "ReportQueries reads DailyEntries, DailyEntryGrades and EggGrades for production and grading totals; ExportQueries streams those records, EggLots and EggInventoryMovements with their existing filters and ordering.",
            [
                "Cluckwork.Infrastructure.Insights.ExportQueries",
                "Cluckwork.Infrastructure.Insights.ReportQueries",
            ]),
        new("Insights", "Farm", "R",
            "ReportQueries.AccountCurrencyAsync reads the current Account currency for report DTOs. The account query remains tenant-filtered and AsNoTracking.",
            ["Cluckwork.Infrastructure.Insights.ReportQueries"]),
        new("Insights", "Finance", "R",
            "ReportQueries aggregates Expenses for expense and profit totals; ExportQueries streams ExpenseCategories and Expenses as typed CSV rows. Neither query writes Finance data.",
            [
                "Cluckwork.Infrastructure.Insights.ExportQueries",
                "Cluckwork.Infrastructure.Insights.ReportQueries",
            ]),
        new("Insights", "FlockManagement", "R",
            "ExportQueries streams Flock and BirdMovement records; ReportQueries reads flock lifecycle and bird movements to calculate hen-day exposure. These are read-only owner-table queries composed in C#.",
            [
                "Cluckwork.Infrastructure.Insights.ExportQueries",
                "Cluckwork.Infrastructure.Insights.ReportQueries",
            ]),
        new("Insights", "GeneralInventory", "R",
            "ExportQueries streams InventoryItems, InventoryLots, InventoryMovements and FeedUsages as typed CSV rows. No inventory mutation or cross-owner SQL join is introduced.",
            ["Cluckwork.Infrastructure.Insights.ExportQueries"]),
    ];
}
