using Cluckwork.Domain.Common.Architecture;

[assembly: ModuleOwner("Access", "module",
    Namespaces = [
        "Cluckwork.Application.Features.Users",
        "Cluckwork.Infrastructure.Identity",
    ],
    Contract = [
        "Cluckwork.Application.Features.Users.IAccessModule",
        "Cluckwork.Application.Features.Users.IAccessLookup",
        "Cluckwork.Application.Features.Users.ICredentialEpochVerifier",
        "Cluckwork.Application.Features.Users.IRefreshTokenPurge",
        "Cluckwork.Application.Features.Users.IAccessOperations",
        "Cluckwork.Application.Features.Users.IAccessAccountLifecycle",
        "Cluckwork.Application.Features.Users.IAccessSeedLookup",
        "Cluckwork.Application.Features.Users.IAccessFixture",
        "Cluckwork.Application.Features.Users.CredentialVerdict",
        "Cluckwork.Application.Features.Users.UserFlockAssignment",
        "Cluckwork.Application.Features.Users.AccessActor",
        "Cluckwork.Application.Features.Users.AccessUserSummary",
        "Cluckwork.Application.Features.Users.FirstRunAdminOutcome",
        "Cluckwork.Application.Features.Users.AdminRecoveryResult",
        "Cluckwork.Application.Features.Users.AccountProvisionOutcome",
        "Cluckwork.Application.Features.Users.AccountLifecycleOutcome",
        "Cluckwork.Application.Features.Users.AccountRenameOutcome",
        "Cluckwork.Application.Features.Users.CreateUser.CreateUserCommand",
        "Cluckwork.Application.Features.Users.UpdateUser.UpdateUserCommand",
        "Cluckwork.Application.Features.Users.SetUserPassword.SetUserPasswordCommand",
        "Cluckwork.Application.Features.Users.ChangeUserRole.ChangeUserRoleCommand",
        "Cluckwork.Application.Features.Users.ChangeUserEmail.ChangeUserEmailCommand",
        "Cluckwork.Application.Features.Users.DisableUser.DisableUserCommand",
        "Cluckwork.Application.Features.Users.EnableUser.EnableUserCommand",
        "Cluckwork.Application.Features.Users.AssignFlock.AssignFlockCommand",
        "Cluckwork.Application.Features.Users.AssignFlock.UnassignFlockCommand",
        "Cluckwork.Application.Features.Users.SetLanguage.SetLanguageCommand",
        "Cluckwork.Application.Features.Users.SetStepperUnit.SetStepperUnitCommand",
        "Cluckwork.Application.Features.Users.ChangeOwnPassword.ChangeOwnPasswordCommand",
    ],
    Implementations = [
        "Cluckwork.Infrastructure.Repositories.UserRoleAssignmentRepository",
    ],
    Types = [
        "Cluckwork.Application.Common.IIdentityProvider",
        "Cluckwork.Application.Common.IStepUpGrantService",
    ])]
[assembly: ModuleOwner("Farm", "module",
    Namespaces = [
        "Cluckwork.Domain.Accounts",
        "Cluckwork.Domain.Media",
        "Cluckwork.Application.Features.Accounts",
    ],
    Contract = [
        "Cluckwork.Application.Features.Accounts.IFarmModule",
        "Cluckwork.Application.Features.Accounts.IFarmFixture",
        "Cluckwork.Application.Features.Accounts.FarmSettingsDetails",
        "Cluckwork.Application.Features.Accounts.FarmBrandingHashes",
        "Cluckwork.Application.Features.Accounts.FarmLogoMetadata",
        "Cluckwork.Application.Features.Accounts.FarmLogoContent",
        "Cluckwork.Application.Features.Accounts.UpdateFarmSettings.UpdateFarmSettingsCommand",
        "Cluckwork.Application.Features.Accounts.IFarmDirectory",
        "Cluckwork.Application.Features.Accounts.FarmTimeZone",
        "Cluckwork.Application.Features.Accounts.FarmListing",
    ],
    Implementations = [
        "Cluckwork.Infrastructure.Repositories.AccountRepository",
        "Cluckwork.Infrastructure.Repositories.FarmFixture",
        "Cluckwork.Infrastructure.Repositories.FarmLogoRepository",
    ],
    Seam = [
        "Cluckwork.Application.Features.Accounts.IAccountRepository",
        "Cluckwork.Domain.Accounts.Account",
        "Cluckwork.Domain.Accounts.UserRoleAssignment",
    ])]
[assembly: ModuleOwner("FlockManagement", "module",
    Namespaces = [
        "Cluckwork.Domain.Flocks",
        "Cluckwork.Application.Features.Flocks",
    ],
    Contract = [
        "Cluckwork.Application.Features.Flocks.IFlockModule",
        "Cluckwork.Application.Features.Flocks.IFlockFixture",
        "Cluckwork.Application.Features.Flocks.FlockFixtureCounts",
        "Cluckwork.Application.Features.Flocks.IFlockLookup",
        "Cluckwork.Application.Features.Flocks.IMortalityLedger",
        "Cluckwork.Application.Features.Flocks.FlockDetails",
        "Cluckwork.Application.Features.Flocks.FlockReference",
        "Cluckwork.Application.Features.Flocks.FlockNameResolution",
        "Cluckwork.Application.Features.Flocks.BirdMovementDetails",
        "Cluckwork.Application.Features.Flocks.FlockEligibility",
        "Cluckwork.Application.Features.Flocks.CreateFlock.CreateFlockCommand",
        "Cluckwork.Application.Features.Flocks.UpdateFlock.UpdateFlockCommand",
        "Cluckwork.Application.Features.Flocks.RecordBirdMovement.RecordBirdMovementCommand",
        "Cluckwork.Domain.Flocks.FlockStatus",
        "Cluckwork.Domain.Flocks.BirdMovementType",
    ],
    Implementations = [
        "Cluckwork.Infrastructure.Repositories.BirdMovementRepository",
        "Cluckwork.Infrastructure.Repositories.FlockFixture",
        "Cluckwork.Infrastructure.Repositories.FlockRepository",
    ])]
[assembly: ModuleOwner("EggOperations", "module",
    Namespaces = [
        "Cluckwork.Domain.Eggs",
        "Cluckwork.Application.Features.DailyEntries",
        "Cluckwork.Application.Features.EggGrades",
        "Cluckwork.Application.Features.EggLots",
        "Cluckwork.Application.Features.Eggs",
    ],
    Contract = [
        "Cluckwork.Application.Features.Eggs.IEggOperationsModule",
        "Cluckwork.Application.Features.Eggs.IEggOperationsFixture",
        "Cluckwork.Application.Features.Eggs.EggOperationsFixtureCounts",
        "Cluckwork.Application.Features.EggGrades.IEggGradeLookup",
        "Cluckwork.Application.Features.EggLots.IEggStock",
        "Cluckwork.Application.Features.EggLots.IEggStockReservation",
        "Cluckwork.Application.Features.EggLots.SaleDemandLine",
        "Cluckwork.Application.Features.EggLots.PlannedEggLotDraw",
        "Cluckwork.Application.Features.EggLots.SaleAllocationPlan",
        "Cluckwork.Application.Features.DailyEntries.IDailyEntryLookup",
        "Cluckwork.Application.Features.Eggs.DailyEntryDetails",
        "Cluckwork.Application.Features.Eggs.EggGradeDetails",
        "Cluckwork.Application.Features.Eggs.EggLotDetails",
        "Cluckwork.Application.Features.Eggs.EggLotMovementDetails",
        "Cluckwork.Application.Features.EggLots.StockByGrade",
        "Cluckwork.Application.Features.DailyEntries.LockDueDailyEntries.DailyEntryLockPass",
        "Cluckwork.Application.Features.DailyEntries.LockDueDailyEntries.LockedDailyEntry",
        "Cluckwork.Application.Features.DailyEntries.LockDueDailyEntries.RefusedDailyEntryLock",
        "Cluckwork.Application.Features.DailyEntries.RecordDailyEntry.RecordDailyEntryCommand",
        "Cluckwork.Application.Features.DailyEntries.RecordDailyEntry.GradeQuantityDto",
        "Cluckwork.Application.Features.DailyEntries.SubmitDailyEntry.SubmitDailyEntryResponse",
        "Cluckwork.Application.Features.DailyEntries.AdjustDailyEntry.AdjustDailyEntryCommand",
        "Cluckwork.Application.Features.DailyEntries.AdjustDailyEntry.AdjustDailyEntryResponse",
        "Cluckwork.Application.Features.DailyEntries.VoidDailyEntry.VoidDailyEntryCommand",
        "Cluckwork.Application.Features.DailyEntries.VoidDailyEntry.VoidDailyEntryResponse",
        "Cluckwork.Application.Features.EggGrades.CreateEggGrade.CreateEggGradeCommand",
        "Cluckwork.Application.Features.EggGrades.UpdateEggGrade.UpdateEggGradeCommand",
        "Cluckwork.Application.Features.EggLots.RecordEggLotMovement.RecordEggLotMovementCommand",
        "Cluckwork.Application.Features.EggLots.RecordEggLotMovement.RecordEggLotMovementResult",
        "Cluckwork.Domain.Eggs.DailyEntryStatus",
        "Cluckwork.Domain.Eggs.DailyEntryKind",
        "Cluckwork.Domain.Eggs.EggGradeType",
        "Cluckwork.Domain.Eggs.EggMovementType",
    ],
    Implementations = [
        "Cluckwork.Infrastructure.Repositories.EggOperationsFixture",
        "Cluckwork.Infrastructure.Repositories.DailyEntryRepository",
        "Cluckwork.Infrastructure.Repositories.EggGradeRepository",
        "Cluckwork.Infrastructure.Repositories.EggInventoryMovementRepository",
        "Cluckwork.Infrastructure.Repositories.EggLotRepository",
    ])]
[assembly: ModuleOwner("Commerce", "module",
    Namespaces = [
        "Cluckwork.Domain.Catalog",
        "Cluckwork.Domain.Sales",
        "Cluckwork.Application.Features.Catalog",
        "Cluckwork.Application.Features.Customers",
        "Cluckwork.Application.Features.Sales",
    ],
    Contract = [
        "Cluckwork.Application.Features.Sales.ICommerceModule",
        "Cluckwork.Application.Features.Sales.ICommerceFixture",
        "Cluckwork.Application.Features.Sales.CommerceFixtureCounts",
        "Cluckwork.Application.Features.Catalog.IEggUnitConversionLookup",
        "Cluckwork.Application.Features.Sales.ProductDetails",
        "Cluckwork.Application.Features.Catalog.EggUnitConversionDetails",
        "Cluckwork.Application.Features.Sales.CustomerDetails",
        "Cluckwork.Application.Features.Customers.CustomerReference",
        "Cluckwork.Application.Features.Sales.SalesOrderDetails",
        "Cluckwork.Application.Features.Sales.SalesOrderItemDetails",
        "Cluckwork.Application.Features.Sales.SalesOrderListItem",
        "Cluckwork.Application.Features.Sales.SalesOrderListFilter",
        "Cluckwork.Application.Features.Sales.SettlementScope",
        "Cluckwork.Application.Features.Sales.PaymentDetails",
        "Cluckwork.Application.Features.Sales.CustomerBalance",
        "Cluckwork.Application.Features.Catalog.CreateProduct.CreateProductCommand",
        "Cluckwork.Application.Features.Catalog.UpdateProduct.UpdateProductCommand",
        "Cluckwork.Application.Features.Catalog.UpdateEggUnitConversion.UpdateEggUnitConversionCommand",
        "Cluckwork.Application.Features.Customers.CreateCustomer.CreateCustomerCommand",
        "Cluckwork.Application.Features.Customers.UpdateCustomer.UpdateCustomerCommand",
        "Cluckwork.Application.Features.Sales.CreateSalesOrder.CreateSalesOrderCommand",
        "Cluckwork.Application.Features.Sales.AddOrderItem.AddOrderItemCommand",
        "Cluckwork.Application.Features.Sales.UpdateOrderItem.UpdateOrderItemCommand",
        "Cluckwork.Application.Features.Sales.ConfirmSale.ConfirmSaleCommand",
        "Cluckwork.Application.Features.Sales.ConfirmSale.ConfirmSaleResponse",
        "Cluckwork.Application.Features.Sales.VoidSale.VoidSaleCommand",
        "Cluckwork.Application.Features.Sales.VoidSale.VoidSaleResponse",
        "Cluckwork.Application.Features.Sales.RecordPayment.RecordPaymentCommand",
        "Cluckwork.Application.Features.Sales.VoidPayment.VoidPaymentCommand",
        "Cluckwork.Domain.Catalog.ProductType",
        "Cluckwork.Domain.Catalog.ProductUnit",
        "Cluckwork.Domain.Catalog.EggUnit",
        "Cluckwork.Domain.Sales.SalesOrderStatus",
        "Cluckwork.Domain.Sales.DiscountReasonCode",
        "Cluckwork.Domain.Sales.ListPriceBasis",
        "Cluckwork.Domain.Sales.PaymentMethod",
    ],
    Implementations = [
        "Cluckwork.Infrastructure.Repositories.CustomerRepository",
        "Cluckwork.Infrastructure.Repositories.CommerceFixture",
        "Cluckwork.Infrastructure.Repositories.EggUnitConversionRepository",
        "Cluckwork.Infrastructure.Repositories.PaymentRepository",
        "Cluckwork.Infrastructure.Repositories.ProductRepository",
        "Cluckwork.Infrastructure.Repositories.SalesOrderAllocationRepository",
        "Cluckwork.Infrastructure.Repositories.SalesOrderRepository",
    ])]
[assembly: ModuleOwner("GeneralInventory", "module",
    Namespaces = [
        "Cluckwork.Domain.Inventory",
        "Cluckwork.Application.Features.Inventory",
    ],
    Contract = [
        "Cluckwork.Application.Features.Inventory.IInventoryModule",
        "Cluckwork.Application.Features.Inventory.IInventoryFixture",
        "Cluckwork.Application.Features.Inventory.InventoryFixtureCounts",
        "Cluckwork.Application.Features.Inventory.InventoryItemDetails",
        "Cluckwork.Application.Features.Inventory.InventoryLotDetails",
        "Cluckwork.Application.Features.Inventory.InventoryMovementDetails",
        "Cluckwork.Application.Features.Inventory.FeedUsageDetails",
        "Cluckwork.Application.Features.Inventory.WaterUsageDetails",
        "Cluckwork.Application.Features.Inventory.CreateInventoryItem.CreateInventoryItemCommand",
        "Cluckwork.Application.Features.Inventory.UpdateInventoryItem.UpdateInventoryItemCommand",
        "Cluckwork.Application.Features.Inventory.RecordPurchase.RecordPurchaseCommand",
        "Cluckwork.Application.Features.Inventory.RecordAdjustment.RecordAdjustmentCommand",
        "Cluckwork.Application.Features.Inventory.RecordFeedUsage.RecordFeedUsageCommand",
        "Cluckwork.Application.Features.Inventory.RecordFeedUsage.RecordFeedUsageResponse",
        "Cluckwork.Application.Features.Inventory.RecordWaterUsage.RecordWaterUsageCommand",
        "Cluckwork.Application.Features.Inventory.UpdateWaterUsage.UpdateWaterUsageCommand",
    ],
    Implementations = [
        "Cluckwork.Infrastructure.Repositories.FeedUsageRepository",
        "Cluckwork.Infrastructure.Repositories.InventoryFixture",
        "Cluckwork.Infrastructure.Repositories.InventoryItemRepository",
        "Cluckwork.Infrastructure.Repositories.InventoryLotRepository",
        "Cluckwork.Infrastructure.Repositories.InventoryMovementRepository",
        "Cluckwork.Infrastructure.Repositories.WaterUsageRepository",
    ])]
[assembly: ModuleOwner("Finance", "module",
    Namespaces = [
        "Cluckwork.Domain.Expenses",
        "Cluckwork.Application.Features.Expenses",
    ],
    Contract = [
        "Cluckwork.Application.Features.Expenses.IFinanceModule",
        "Cluckwork.Application.Features.Expenses.IFinanceFixture",
        "Cluckwork.Application.Features.Expenses.FinanceFixtureCounts",
        "Cluckwork.Application.Features.Expenses.ExpenseCategoryDetails",
        "Cluckwork.Application.Features.Expenses.ExpenseDetails",
        "Cluckwork.Application.Features.Expenses.ExpenseListPage",
        "Cluckwork.Application.Features.Expenses.CreateExpenseCategory.CreateExpenseCategoryCommand",
        "Cluckwork.Application.Features.Expenses.UpdateExpenseCategory.UpdateExpenseCategoryCommand",
        "Cluckwork.Application.Features.Expenses.CreateExpense.CreateExpenseCommand",
        "Cluckwork.Application.Features.Expenses.AdjustExpense.AdjustExpenseCommand",
    ],
    Implementations = [
        "Cluckwork.Infrastructure.Repositories.ExpenseCategoryRepository",
        "Cluckwork.Infrastructure.Repositories.ExpenseRepository",
        "Cluckwork.Infrastructure.Repositories.FinanceFixture",
    ])]
[assembly: ModuleOwner("Insights", "module",
    Namespaces = [
        "Cluckwork.Application.Features.Audit",
        "Cluckwork.Application.Features.Reports",
        "Cluckwork.Application.Features.Export",
        "Cluckwork.Application.Features.Insights",
        "Cluckwork.Infrastructure.Insights",
    ],
    Contract = [
        "Cluckwork.Application.Features.Insights.IInsightsModule",
        "Cluckwork.Application.Features.Insights.AuditEventRead",
        "Cluckwork.Application.Features.Audit.EntityProvenance",
        "Cluckwork.Application.Features.Export.ExportDataset",
        "Cluckwork.Application.Features.Reports.ProductionReport",
        "Cluckwork.Application.Features.Reports.ProductionDay",
        "Cluckwork.Application.Features.Reports.GradeTotal",
        "Cluckwork.Application.Features.Reports.SalesSummary",
        "Cluckwork.Application.Features.Reports.ExpenseSummary",
        "Cluckwork.Application.Features.Reports.ExpenseCategoryTotal",
        "Cluckwork.Application.Features.Reports.ProfitReport",
    ])]
[assembly: ModuleOwner("Platform", "platform",
    Namespaces = [
        "Cluckwork.Domain.Common",
        "Cluckwork.Domain.Auditing",
        "Cluckwork.Application.Common",
        "Cluckwork.Infrastructure",
        "Cluckwork.Api",
        "Cluckwork.AppHost",
    ],
    ExactNamespaces = [
        "Cluckwork.Domain",
        "Cluckwork.Application",
    ])]
