// tools/simulation/ui/src/cast.ts — who the personas are, and what they can do.
//
// Credentials come from `tools/simulation/.sim-cast.json`, generated by
// bootstrap.sh and git-ignored. NEVER inline a value from it here: GitGuardian
// scans PRs and flags a credential-shaped literal even inside a test file, and
// even in a diff that REMOVES one. k6 reads the same file (k6/config.js) — one
// fixture, two harnesses.
//
// ================== THE CAST FILE'S `role` IS DESCRIPTIVE ==================
//
// `.sim-cast.json` says so itself, in its own `notes`: a Worker entry carries no
// Identity role row at all, so "role": "Worker" there is a label for humans, not
// something the app ever sees. What the SPA actually derives (claims.ts) was
// confirmed by logging every persona in against the live stack and decoding the
// JWT, rather than by trusting either the file or the seeder's variable names:
//
//   cast "Owner"    -> JWT role claim "Admin"     -> SPA Role "Admin"     (isAdmin)
//   cast "Manager"  -> JWT role claim "Manager"   -> SPA Role "Manager"   (isAdmin)
//   cast "Sales"    -> JWT role claim "Sales"     -> SPA Role "Sales"
//   cast "Worker"   -> NO role claim at all       -> SPA Role "Worker"
//   cast "ReadOnly" -> JWT role claim "ReadOnly"  -> SPA Role "ReadOnly"
//
// That "Owner" -> "Admin" step is the one that bites: a spec asserting on the
// string "Owner" would be asserting on a label the application never uses.

import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";

/** The role vocabulary the SPA itself derives from the JWT (web/src/auth/claims.ts). */
export type SpaRole = "Admin" | "Manager" | "Sales" | "ReadOnly" | "Worker" | "Denied";

/** The descriptive label used in `.sim-cast.json` and by SimulationDataSeeder. */
export type CastRole = "Owner" | "Manager" | "Sales" | "Worker" | "ReadOnly";

export interface CastMember {
  email: string;
  password: string;
  /** The cast file's own label. Use `spaRole` for anything the app will actually see. */
  role: CastRole;
  /** What claims.ts will derive for this member once signed in. */
  spaRole: SpaRole;
  /** What `currentUserIsAdmin()` will return — Admin or Manager. */
  isAdmin: boolean;
}

interface RawCastFile {
  generatedAt: string;
  emailDomain: string;
  owner: { email: string; password: string; role: CastRole };
  cast: Array<{ email: string; password: string; role: CastRole }>;
}

const CAST_PATH = fileURLToPath(new URL("../../.sim-cast.json", import.meta.url));

/**
 * cast label -> the Role the SPA will derive. Kept as an explicit table rather
 * than a clever mapping, because the two vocabularies genuinely differ by more
 * than casing and the difference is the whole point of this module.
 */
const SPA_ROLE_FOR: Record<CastRole, SpaRole> = {
  Owner: "Admin",
  Manager: "Manager",
  Sales: "Sales",
  Worker: "Worker",
  ReadOnly: "ReadOnly",
};

function decorate(raw: { email: string; password: string; role: CastRole }): CastMember {
  const spaRole = SPA_ROLE_FOR[raw.role];
  if (!spaRole) {
    throw new Error(
      `.sim-cast.json contains an unknown role "${raw.role}" for ${raw.email}. `
        + `SimulationDataSeeder's cast vocabulary changed — update SPA_ROLE_FOR in cast.ts.`,
    );
  }
  return { ...raw, spaRole, isAdmin: spaRole === "Admin" || spaRole === "Manager" };
}

let cached: CastMember[] | null = null;

/** Every cast member, owner first. Read once per process. */
export function loadCast(): CastMember[] {
  if (cached) return cached;

  let raw: RawCastFile;
  try {
    raw = JSON.parse(readFileSync(CAST_PATH, "utf8")) as RawCastFile;
  } catch (cause) {
    throw new Error(
      `Could not read the simulation cast at ${CAST_PATH}. `
        + `Run \`bash tools/simulation/bootstrap.sh\` (then \`reset.sh\`) to generate it.`,
      { cause },
    );
  }

  cached = [decorate(raw.owner), ...raw.cast.map(decorate)];
  return cached;
}

/**
 * The FIRST cast member with this label — deterministic, because
 * SimulationDataSeeder numbers them (`sim-worker-1`, `sim-worker-2`, …) and
 * seeds them in order.
 *
 * That ordering is load-bearing for exactly one persona: the seeder's
 * `RestrictOneWorkerAsync` restricts `workerIds[0]` — i.e. `sim-worker-1` — to a
 * single flock. `restrictedWorker()` below exists so no spec has to re-derive
 * that from the seeder's source.
 */
export function castMember(role: CastRole): CastMember {
  const found = loadCast().find((m) => m.role === role);
  if (!found) {
    throw new Error(
      `No "${role}" in the simulation cast. Check Simulation__${role}s in `
        + `tools/simulation/.env.sim — a count of 0 seeds nobody.`,
    );
  }
  return found;
}

/** The Owner. `.sim-cast.json` puts them outside the `cast` array; loadCast() puts them first. */
export function owner(): CastMember {
  return castMember("Owner");
}

/**
 * The one worker SimulationDataSeeder deliberately narrowed to a single flock.
 *
 * Note what this restriction actually does, because it is NOT what #277 assumed
 * and the difference is now #388: it gates the production **write** path
 * (`422 FlockScope.NotAssigned`) and nothing else. Every read — the flock list,
 * a flock's detail, another flock's 90 days of daily entries — answers 200 for
 * this worker exactly as it does for an unrestricted one. Assert the write.
 */
export function restrictedWorker(): CastMember {
  return castMember("Worker");
}

/**
 * A worker with NO flock restriction — the control case for the #388 write
 * assertion, so "the refusal happened because of the assignment" is a
 * comparison rather than an assumption.
 */
export function unrestrictedWorker(): CastMember {
  const workers = loadCast().filter((m) => m.role === "Worker");
  if (workers.length < 2) {
    throw new Error(
      `The flock-restriction spec needs at least 2 workers (one restricted, one not); `
        + `the cast has ${workers.length}. Raise Simulation__Workers in tools/simulation/.env.sim.`,
    );
  }
  return workers[1]!;
}
